= Getting started with Bitcoin Core

This document was created from Bitcoin Core at commit https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e[4b5659c6]

WARNING: Whilst this disclaimer is present this documentation is considered a work in progress and may be subject to minor or major changes at any time without notice.

WARNING: This documentation can temporarily be found hosted at https://obc.256k1.dev[], however the hosted location is likely to change in the near future.

== Building Bitcoin Core from source

When building Bitcoin Core from source, there are some platform-dependant instructions to follow.

To learn how to build for your platform, visit the Bitcoin Core https://github.com/bitcoin/bitcoin/tree/master/doc[bitcoin/doc] directory, and read the file named "build-\*.md", where "*" is the name of your platform.
For windows this is "build-windows.md", for macOS this is "build-osx.md" and for most linux distributions this is "build-unix.md".

There is also a guide by Jon Atack about how to https://jonatack.github.io/articles/how-to-compile-bitcoin-core-and-run-the-tests[compile and test Bitcoin Core].

=== Doxygen documentation

Bitcoin Core uses https://www.doxygen.nl/index.html[Doxygen] to generate developer documentation automatically from its annotated C++ codebase.
Developers can access documentation of the current release of Bitcoin Core online at https://doxygen.bitcoincore.org/[doxygen.bitcoincore.org], or alternatively can generate documentation for their current head using `make docs` (see https://github.com/bitcoin/bitcoin/tree/master/doc/developer-notes.md#generating-documentation[Generating Documentation] for more info).

== Bitcoin contributor journeys

Some contributors have documented their journeys into the space which let's us learn about approaches they found useful, but also any pitfalls and things they found difficult along the way.

* https://github.com/amitiuttarwar[Amiti Uttarwar] - https://medium.com/@amitiu/onboarding-to-bitcoin-core-7c1a83b20365[Onboarding to Bitcoin Core]
* https://github.com/jonatack[Jon Atack] - https://jonatack.github.io/articles/on-reviewing-and-helping-those-who-do-it[On Reviewing, and Helping Those Who Do It]
* https://github.com/jimmysong[Jimmy Song] - https://bitcointechtalk.com/a-gentle-introduction-to-bitcoin-core-development-fdc95eaee6b8[A Gentle Introduction to Bitcoin Core Development]

== Bitcoin Core and GitHub

Bitcoin Core uses a GitHub-based workflow for development.
The primary function of GitHub in the workflow is to discuss patches and connect them with review comments.

Whilst some other prominent projects, e.g. the Linux kernel use email for soliciting feedback and review, Bitcoin Core has used GitHub for many years.
Initially Satoshi distributed the code through private emails and hosting source archives at bitcoin.org, and later by hosting on SourceForge (which used SVN but did not at that time have a pull request system like GitHub).
The earliest reviewers submitted changes using patches either through email exchange with Satoshi, or by posting them on the bitcoin forum.

In August 2009, the source code was moved to GitHub by Sirius and development has remained there and used the GitHub workflows ever since.

=== Organisation & roles

Anyone who contributes code to the codebase is labelled a "contributor" by GitHub (and the community).
As of Version 22.0 of Bitcoin Core, there are ~820 individual contributors credited with changes.

Some contributors are also labelled as "members" of the https://github.com/orgs/bitcoin/people[Bitcoin Core organisation].
There are currently ~30 members of the organisation.
These members are usually frequent contributors and have good technical knowledge of the codebase.
Members also have some additional permissions over contributors, such as adding/removing tags on issues and PRs, however being a member does not permit you to merge PRs into the project.
Members can also be assigned sections of the codebase (where they might have expertise and) where they can be more easily requested for review as "suggested reviewers", by PR authors.

NOTE: In a normal workflow it is not necessary (or desirable) to request reviews from suggested reviewers, and in fact doing so without a "good reason" might be interpreted as being too pushy, having the opposite result than intended.

Some members are also project "maintainers".
There are currently 7 maintainers on the Bitcoin Core project, but this number is arbitrary and is subject to change as people join and leave the project.
PRs can only be merged into the main project by "maintainers".
Whilst this might give the illusion that maintainers are in "control" of the project, the maintainers' role dictates that they *should not* be unilaterally deciding what PRs are merged and which aren't.
Instead they should be determining mergability of changes primarily based on the reviews and discussions of other contributors on the PR itself, on GitHub (or less commonly the https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-core-dev[#bitcoin-core-dev] mailing list).

Working on that basis, the maintainers' role becomes largely "janitorial" in that they are simply executing the desires of the community review process; a community which is made up of a decentralised and diverse group of contributors.

A list of maintainers and suggested reviewers can be found in the https://github.com/bitcoin/bitcoin/tree/master/REVIEWERS[REVIEWERS] document.
As the document states, these are NOT the only people who should be reviewing PRs.
The project needs as many reviews on each PR as possible, ideally from a diverse range of reviewers.

The objective of the Bitcoin Core Organisation is therefore to represent an entity that is decentralised as much as practically possible, on a centralised platform.
One where no single contributor, member or maintainer has unilateral control over what is/isn't merged into the project.
Having multiple maintainers, members, contributors and reviewers gives this objective the best chance of being realised.

==== Organisation fail-safes

It is possible for a "rogue" PR to be submitted by a contributor, however we rely on the thorough peer review process to catch these.
There has recently been discussion on the mailing list about https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-September/019490.html[purposefully testing malicious PRs] to test this property of the review process even further.

In the event that a maintainer goes rogue and starts merging controversial code, or conversely _not_ merging changes which are desired by the community at large, then there are two possible avenues of recourse for users:

. Have the "lead maintainer" remove the malicious maintainer
. In the case that the lead maintainer themselves is considered to be the "rogue" agent: fork the project to a new location and continue development there.

In the case that GitHub itself becomes the rogue entity, there have been numerous https://github.com/bitcoin/bitcoin/issues/20227[discussions about how to move away from GitHub], should the need ever arise.

=== Github workflow

The GitHub side of the Bitcoin Core workflow for contributors consists primarily of:

* Issues
* PRs
* Reviews
* Comments

Generally, issues are used for two purposes:

. Posting known issues with software, e.g. bug reports, crash logs
. Soliciting feedback on potential changes without providing associated code, as would be required in a PR.

GitHub provides their own https://guides.github.com/features/issues/[guide on mastering issues] which is worth reading to understand the feature-set available when working with an issue.

PRs are where contributors can submit their code against the main codebase and solicit feedback on the concept, the approach taken for the implementation, and the actual implementation itself.

PRs and issues are often linked to/from one another:

[example]
====
One common workflow is when an issue is opened to report a bug.
After replicating the issue, a contributor creates a patch and then opens a PR with their proposed changes.

In this case the contributor should, in addition to comments about the patch, reference that the patch fixes the issue.
For a patch which fixes issue 22889 this would be done by writing "fixes #22889" in the PR description or in a commit message.
In this case the syntax "fixes #issue-number" is caught by GitHub's https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue[pull request linker].
====

Another use of issues is for getting feedback on ideas which might require *significant* changes.
This helps free the project from having too many PRs open which aren't ready for review, and might waste reviewers' time.
In addition this workflow can also save contributors their _own_ valuable time, as a idea might be identified as unlikely to be accepted before the contributor spends their time writing the code for it.

Most code changes to bitcoin are proposed directly as PRs -- there's no need to open an issue for every idea before implementing it, unless it will require significant changes.
Additionally, other contributors (and would-be reviewers) will often agree with the approach of a change, but want to "see the implementation" before they can really pass judgement on it.

Reviews help to store and track reviews to PRs in a public way.

Comments (inside issues, PRs, discussions etc.) are where users can discuss relevant aspects of the item and have history of those discussions preserved for future reference.
Often contributors having "informal" discussions about changes on e.g. IRC will be advised that they should echo the gist of their conversation as a comment so that the rationale behind changes can be determined in the future.

== Research topics/questions

* What stops a hacker hijacking the Bitcoin Core website and hosting malicious binaries?
** How about malicious binaries hosted by linux package managers?
* Where can you go for help if Bitcoin Core doesn't build on your machine?
* Before you create a PR to the main bitcoin core repo, what checks should you do locally?
** Are there any additional checks you can think of which are only run in the bitcoin core repo (and not your fork)?

== Solo work

=== Git exercises

* Understand lsilva01's https://github.com/lsilva01/operating-bitcoin-core-v1/blob/main/git-tutorial.md[git tutorial for Bitcoin Core]
* https://chris.beams.io/posts/git-commit/[Write good commit messages]

=== GitHub workflow basics

* Fork the https://github.com/bitcoin/bitcoin[bitcoin core repository]
** GitHub provides a guide on how to https://guides.github.com/activities/forking/[fork a project]
* Download a clone of your fork of the bitcoin project to your local machine
* Checkout a tag, branch or PR

=== Building bitcoin from source

* Compile the source code you cloned
* Run the tests
. https://github.com/bitcoin/bitcoin/tree/master/test[Project test overview]
. https://github.com/chaincodelabs/bitcoin-core-onboarding/blob/main/functional_test_framework.asciidoc[Functional test suite]
. Also see https://github.com/bitcoin/bitcoin/tree/master/test#running-the-tests[Bitcoin Core, running the tests]
. https://github.com/bitcoin/bitcoin/tree/master/src/test/README.md[Bitcoin Core, unit tests]

=== Review a PR

* Find a PR (which can be open or closed) on GitHub which looks interesting and/or accessible
* Checkout the PR locally
* Review the changes
** Record any questions that arise during code review
* Build the PR
* Test the PR
* Break a test / add a new test
* Leave review feedback on GitHub, possibly including:
** ACK/NACK
** Approach
** How you reviewed it
** Your system specifications if relevant
** Suggesting nits

=== Create a test using test framework

* You can refer to the }https://github.com/chaincodelabs/bitcoin-core-onboarding/blob/main/functional_test_framework.asciidoc[Functional Test Framework] doc
* Try and write a new functional test which can send p2p messages between nodes
+
TIP: starting with `ping` and `pong` messages might be easiest
* Try writing a more advanced test

== Group work

* Each submit a PR on a team member's fork of Bitcoin Core (not the main repo)
* Review a different team member's PR
* Submit your review of the PR as a GitHub comment on the PR

// == Removed text
//
// === Goals
//
// * Learn how the Bitcoin Core project uses GitHub
// * Learn how to compile the code from source
// * Learn how to run the test suite
// * Learn about other developers journeys into bitcoin dev
// * PR review process
//
// === Concepts
//
// * GitHub usage
// * Git usage
// * Building bitcoin from source code
// * Running the test suite
