= Architecture

TIP: This section has been updated to Bitcoin Core @ https://github.com/bitcoin/bitcoin/tree/v23.0[v23.0^]

== bitcoind overview

The following diagram gives a brief overview of how some of the major components in bitcoind are related.

WARNING: This diagram is **not** exhaustive and includes simplifications.

NOTE: dashed lines indicate optional components

.`bitcoind` overview
[mermaid, target=bitcoind-overview, format=svg, id=bitcoind-overview]
....
flowchart LR
    bitcoind
    RPCServer -.-> bitcoind
    RESTServer -.-> bitcoind
    Node -----> bitcoind
    AddrMan --> Node
    CConnman --> Node
    Interfaces::Chain --> Node
    ChainstateManager --> Node
    NetGroupManager --> AddrMan
    CTxMemPool --> Node
    PeerManager --> Node
    Wallet -.-> bitcoind
    ScriptPubKeyMan --> Wallet
    WalletDatabase --> Wallet
    sqlite -.-> WalletDatabase
    BDB -.-> WalletDatabase
    Logger --> bitcoind
    ZMQ -.-> bitcoind
    BlockManager --> ChainstateManager
    LevelDB --> BlockManager
....

.Brief description of components in <<bitcoind-overview>>
[%autowidth]
|===
|Component |Simplified description

|`AddrMan`
|Manage peers' network addresses

|`CConnman`
|Manage network connections to peers

|`Interfaces::Chain`
|Give clients access to chain state, fee rate estimates, notifications and allow tx submission

|`ChainstateManager`
|An interface for interacting with 1 or 2 chainstates (1. IBD-verified, 2. optional snapshot)

|`NetGroupManager`
|Manage net groups. Ensure we don't connect to multiple nodes in the same ASN bucket

|`CTxMemPool`
|Validate and store (valid) transactions which may be included in the next block

|`PeerManager`
|Manage peer state and interaction e.g. processing messages, fetching blocks & removing for misbehaviour

|`BlockManager`
|Maintains a tree of blocks on disk (via LevelDB) to determine most-work tip

|`ScriptPubKeyMan`
|Manages `scriptPubKeys` in a wallet. Can give out new `scriptPubKeys` as well as call into a `SigningProvider` to sign transactions

|===

== Wallet structure

The following diagram gives a brief overview of how the wallet is structured.

WARNING: This diagram is **not** exhaustive and includes simplifications.

NOTE: dashed lines indicate optional components

.Wallet structure overview
[mermaid, target=bitcoin-wallet-overview, format=svg]
....
flowchart LR
    ScriptPubKeyMan --> DescriptorScriptPubKeyMan
    ScriptPubKeyMan --> LegacyScriptPubKeyMan
    subgraph Descriptor or Legacy wallet
    DescriptorScriptPubKeyMan
    LegacyScriptPubKeyMan
    end
    DescriptorScriptPubKeyMan -.-> CWallet
    LegacyScriptPubKeyMan -.-> CWallet
    Interfaces::Chain --> CWallet
    WalletDatabase --> CWallet
    cs_wallet{{cs_wallet}} ---> CWallet

    subgraph BDB or sqlite database
    BDB
    sqlite
    end
    BDB -.-> WalletDatabase
    sqlite -.-> WalletDatabase

    SigningProvider --> ScriptPubKeyMan
    WalletStorage --> ScriptPubKeyMan
    Scripts --> ScriptPubKeyMan
    Keys --> ScriptPubKeyMan
....

.Brief description of components
[%autowidth]
|===
|Component |Simplified description

|`WalletDatabase`
|Represents a single wallet. Handles reads and writes to disk

|`ScriptPubKeyMan`
|Base class for the below SPKM classes to override before being used by `CWallet`

|`DescriptorScriptPubKeyMan`
|A SPKM for https://github.com/bitcoin/bitcoin/pull/16528[descriptor-based^] wallets

|`LegacyScriptPubKeyMan`
|A SPKM for legacy wallets

|`SigningProvider`
|An interface for a `KeyStore` to sign transactions from

|`Interfaces::Chain`
|Give clients access to chain state, fee rate estimates, notifications and allow tx submission

|`cs_wallet`
|The primary wallet lock, held for atomic wallet operations

|===

== `bitcoin-cli` overview

The following diagram gives a brief overview of how bitcoin-cli operates.

WARNING: This diagram is **not** exhaustive and includes simplifications.

.`bitcoin-cli` overview
[mermaid, target=bitcoin-cli-overview, format=svg, id=bitcoin-cli-overview-chart]
....
flowchart LR
    BaseRequestHandler["BaseRequestHandler()"]
    AddrInfoRequestHandler["AddrInfoRequestHandler()"]
    ConnectAndCallRPC["ConnectAndCallRPC()"]
    GetInfoRequestHandler["GetInfoRequestHandler()"]
    NetInfoRequestHandler["NetInfoRequestHandler()"]
    GenerateToAddressHandler["GenerateToAddressHandler()"]
    DefaultRequestHandler["DefaultRequestHandler()"]
    BaseRequestHandler --> AddrInfoRequestHandler --> ConnectAndCallRPC
    BaseRequestHandler --> GetInfoRequestHandler --> ConnectAndCallRPC
    BaseRequestHandler --> NetInfoRequestHandler --> ConnectAndCallRPC
    BaseRequestHandler --> GenerateToAddressHandler --> ConnectAndCallRPC
    BaseRequestHandler --> DefaultRequestHandler --> ConnectAndCallRPC
    ConnectAndCallRPC <---> bitcoin-cli
    ArgsManager --> bitcoin-cli
....

== Tests overview

.Tests overview
[%autowidth]
|===
|Tool |Usage

|unit tests
|`make check` or `./src/test_bitcoin`

|functional tests
|`test/functional/test_runner.py`

|lint checks
|`test/lint/all-lint.py`

|fuzz
|See the https://github.com/bitcoin/bitcoin/blob/master/doc/fuzzing.md[documentation^]

|util tests
|`test/util/test_runner.py`

|===

=== Test directory structure

The following diagram gives a brief overview of how the tests are structured within the source directory.

WARNING: This diagram is **not** exhaustive and includes simplifications.

NOTE: dashed lines indicate optional components

NOTE: The `fuzz_targets` themselves are located in the `test` folder, however the fuzz tests are run via the `test_runner` in src/test so we point fuzz to there.

NOTE: `qa_assets` are found in a https://github.com/bitcoin-core/qa-assets[separate^] repo altogether, as they are quite large (~3.5GB repo size and ~13.4GB on clone).

.Test directory Structure
[mermaid, target=bitcoin-core-tests, format=svg]
....
flowchart LR
    TR1[test_runner]
    functional --> test
    lint --> test
    util --> test
    test_framework --> functional
    TR1 --> functional

    TR2["test_runner (fuzz)"]
    fuzz_targets --> fuzz
    fuzz --> src/test
    libFuzzer -.-> fuzz
    TR2 --> fuzz
    qa-assets -.-> fuzz
    unit --> src/test
    Boost --> unit
    test_bitcoin --> unit

    classDef types fill:green,color:white,stroke:green;
    class functional,lint,util,fuzz,unit types
....

== Threads

The `main()` function starts the main bitcoind process thread, usefully named `bitcoind`.
All subsequent threads are currently started as children of the `bitcoind` thread, although this is not an explicit design requirement.

The Bitcoin Core Developer https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#threads=[docs^] contains a section on threads, which is summarised below in two tables, one for net threads, and one for other threads.

.Non-net threads
[%autowidth]
|===
|Name |Function |Description

|`bitcoind`
|`main()`
|Responsible for starting up and shutting down the application, and spawning all sub-threads

|`b-loadblk`
|`ThreadImport`
|Loads blocks from `blk*.dat` files or `-loadblock=<file>` on startup

|`b-scriptch.x`
|`ThreadScriptCheck`
|Parallel script validation threads for transactions in blocks

|`b-http`
|`ThreadHTTP`
|Libevent thread to listen for RPC and REST connections

|`b-httpworker.x`
|`StartHTTPServer`
|HTTP worker threads. Threads to service RPC and REST requests

|`b-txindex.x`
|`ThreadSync`
|Indexer threads. One thread per indexer

|`b-scheduler`
|`SchedulerThread`
|Does asynchronous background tasks like dumping wallet contents, dumping `addrman` and running asynchronous `validationinterface` callbacks

|`b-torcontrol`
|`TorControlThread`
|Libevent thread for tor connections

|===

=== Net threads

.Net threads
[%autowidth]
|===
|Name |Function |Description

|`b-msghand`
|`ThreadMessageHandler`
|Application level message handling (sending and receiving). Almost all `net_processing` and validation logic runs on this thread

|`b-dnsseed`
|`ThreadDNSAddressSeed`
|Loads addresses of peers from the `ThreadDNS`

|`b-upnp`
|`ThreadMapPort`
|Universal plug-and-play startup/shutdown

|`b-net`
|`ThreadSocketHandler`
|Sends/Receives data from peers on port 8333

|`b-addcon`
|`ThreadOpenAddedConnections`
|Opens network connections to added nodes

|`b-opencon`
|`ThreadOpenConnections`
|Initiates new connections to peers

|`b-i2paccept`
|`ThreadI2PAcceptIncoming`
|Listens for and accepts incoming I2P connections through the I2P SAM proxy

|===

=== Thread debugging

In order to debug a multi-threaded application like bitcoind using gdb you will need to enable following child processes.
Below is shown the contents of a file `threads.brk` which can be sourced into gdb using `source threads.brk`, before you start debugging bitcoind.
The file also loads break points where new threads are spawned.

.threads.brk
[source,bash]
----
set follow-fork-mode child
break node::ThreadImport
break StartScriptCheckWorkerThreads
break ThreadHTTP
break StartHTTPServer
break ThreadSync
break SingleThreadedSchedulerClient
break TorControlThread
break ThreadMessageHandler
break ThreadDNSAddressSeed
break ThreadMapPort
break ThreadSocketHandler
break ThreadOpenAddedConnections
break ThreadOpenConnections
break ThreadI2PAcceptIncoming
----

== Library structure

Bitcoin Core compilation outputs a number of libraries, some which are designed to be used internally, and some which are designed to be re-used by external applications.
The internally-used libraries generally have unstable APIs making them unsuitable for re-use, but `libbitcoin_consensus` and `libbitcoin_kernel` are designed to be re-used by external applications.

Bitcoin Core has a https://github.com/bitcoin/bitcoin/blob/master/doc/design/libraries.md[guide^] which describes the various libraries, their conventions, and their various dependencies.
The dependency graph is shown below for convenience, but may not be up-to-date with the Bitcoin Core document.

[id=library-dependency-graph]
.Bitcoin library dependency graph
[mermaid, target=bitcoin-lib-dependencies, format=svg]
....
flowchart TB
    bitcoin-wallet --> libbitcoin_wallet_tool
    bitcoin-wallet --> libbitcoin_wallet

    bitcoin-qt ---> libbitcoin_wallet
    bitcoin-qt ---> libbitcoinqt
    bitcoin-qt ---> libbitcoin_node

    bitcoind ---> libbitcoin_wallet
    bitcoind --> libbitcoin_node

    bitcoin-cli ---> libbitcoin-cli

    libbitcoin_wallet_tool --> libbitcoin_wallet
    libbitcoin_wallet_tool --> libbitcoin_util

    libbitcoin-cli --> libbitcoin_common
    libbitcoin-cli --> libbitcoin_util

    libbitcoin_node --> libbitcoin_common
    libbitcoin_node --> libbitcoin_consensus
    libbitcoin_node --> libbitcoin_kernel
    libbitcoin_node --> libbitcoin_util

    libbitcoinqt --> libbitcoin_util
    libbitcoinqt --> libbitcoin_common

    libbitcoin_wallet --> libbitcoin_util
    libbitcoin_wallet --> libbitcoin_common

    libbitcoin_common --> libbitcoin_util
    libbitcoin_common --> libbitcoin_consensus

    libbitcoin_kernel --> libbitcoin_consensus
    libbitcoin_kernel --> libbitcoin_util

    classDef types fill:green,color:white,stroke:green;
    class bitcoin-wallet,bitcoind,bitcoin-cli,bitcoin-qt types
....

It follows that API changes to the libraries which are internally-facing can be done slightly easier than for libraries with externally-facing APIs, for which more care for compatibility must be taken.

=== Library source code organization

Issue https://github.com/bitcoin/bitcoin/issues/15732[#15732^] describes how the Bitcoin Core project is striving to organize library files, copied below for convenience:

> Here is how I am thinking about the organization:
> 
>     * `libbitcoin_server.a`, `libbitcoin_wallet.a`, and `libbitcoinqt.a` should all be terminal dependencies. They should be able to depend on other symbols in other libraries, but no other libraries should depend on symbols in them (and they shouldn't depend on each other).
> 
>     * `libbitcoin_consensus.a` should be a standalone library that doesn't depend on symbols in other libraries mentioned here
> 
>     * `libbitcoin_common.a` and `libbitcoin_util.a` seem very interchangeable right now and mutually depend on each other. I think we should either merge them into one library, or create a new top-level `src/common/` directory complementing `src/util/`, and start to distinguish general purpose utility code (like argument parsing) from bitcoin-specific utility code (like formatting bip32 paths and using ChainParams). Both these libraries can be depended on by `libbitcoin_server.a`, `libbitcoin_wallet.a`, and `libbitcoinqt.a`, and they can depend on `libbitcoin_consensus.a`. If we want to split util and common up, as opposed to merging them together, then util shouldn't depend on libconsensus, but common should.
> 
> 
> Over time, I think it'd be nice if source code organization reflected library organization . I think it'd be nice if all `libbitcoin_util` source files lived in `src/util`, all `libbitcoin_consensus.a` source files lived in `src/consensus`, and all `libbitcoin_server.a` code lived in `src/node` (and maybe the library was called `libbitcoin_node.a`).

You can track the progress of these changes by following links from the issue to associated PRs.

The `libbitcoin-kernel` https://github.com/bitcoin/bitcoin/issues/24303[project^] will provide further clean-ups and improvements in this area.

If you want to explore for yourself which sources certain libraries require on the current codebase, you can open the file `src/Makefile.am` and search for `_SOURCES`.

== Deep technical dive (WIP)

lsilva01 has written a deep technical dive into the architecture of Bitcoin Core as part of the Bitcoin Core Onboarding Documentation in https://github.com/chaincodelabs/bitcoin-core-onboarding/blob/main/1.0_bitcoin_core_architecture.asciidoc[Bitcoin Architecture^].

Once you've gained some insight into the architecture of the program itself you can learn further details about which code files implement which functionality from the https://github.com/chaincodelabs/bitcoin-core-onboarding/blob/main/1.1_regions.asciidoc[Bitcoin Core regions^] document.

James O'Beirne has recorded 3 videos which go into detail on how the codebase is laid out, how the build system works, what developer tools there are, as well as what the primary function of many of the files in the codebase are:

. https://www.youtube.com/watch?v=J1Ru8V36z_Y[Architectural tour of Bitcoin Core (part 1 of 3)^]
. https://www.youtube.com/watch?v=RVWcUnpZX4E[Architectural tour of Bitcoin Core (part 2 of 3)^]
. https://www.youtube.com/watch?v=UiD5DZU9Zp4[Architectural tour of Bitcoin Core (part 3 of 3)^]

ryanofsky has written a handy https://github.com/ryanofsky/bitcoin/blob/pr/libs/doc/design/libraries.md[guide^] covering the different libraries contained within Bitcoin Core, along with some of their conventions and a dependency graph for them.
Generally speaking, the desire is for the Bitcoin Core project to become more modular and less monolithic over time.

== Directory structure

TODO: A description of the directory structure

== Subtrees

Several parts of the repository (LevelDB, crc32c, secp256k1 etc.) are subtrees of software maintained elsewhere.

Some of these are maintained by active developers of Bitcoin Core, in which case changes should go directly upstream without being PRed directly against the project.
They will be merged back in the next subtree merge.

Others are external projects without a tight relationship with our project.

There is a tool in `test/lint/git-subtree-check.sh` to check a subtree directory for consistency with its upstream repository.

See the full https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#subtrees[subtrees^] documentation for more information.

== Implementation separation

Many of the classes found throughout the codebase use the PIMPL technique to separate their implementation from the external representation.
See <<pimpl-technique,PIMPL technique>> in the Appendix for more information.
