= P2P

== Design philosophy

Bitcoin Core's P2P design philosophy is outlined in the bitcoin devwiki article https://github.com/bitcoin-core/bitcoin-devwiki/wiki/P2P-Design-Philosophy[P2P Design Philosophy].
A synopsis of the ideas can be found in the first paragraph which states:

[quote]
____
For the Bitcoin network to remain in consensus, the network of nodes must not be partitioned.
So for an individual node to remain in consensus with the network, it must have at least one connection to that network of peers that share its consensus rules.

...

We can't rely on inbound peers to be honest, because they are initiated by others.
It's impossible for us to know, for example, whether all our inbound peers are controlled by the same adversary.

Therefore, in order to try to be connected to the honest network, we focus on having good outbound peers, as we get to choose who those are.
____

The document, which is worth reading in its entirely, continues by assuming the case that we don't have any inbound peers but also considering that any inbound peers we _do_ have can't interfere with the P2P logic proposed.

== Addrman and eclipse attacks

In order to make "at least one connection to that network of peers that share its consensus rules", as the philosophy above targets, a Bitcoin Core node needs to have some node (network) addresses to connect to which are _not_ controlled by a potential attacker.

When the node has never connected to the bitcoin P2P network before it has no choice but to fetch addresses from one (or more) hardcoded DNS seed(s), the list of which can be found in https://github.com/bitcoin/bitcoin/blob/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/chainparams.cpp#L121-L129[_src/chainparams.cpp_].
If the node is fed only attacker-controlled addresses by the seed(s) then it has little/no opportunity to join the rest of the honest network.
However, if one or more of the addresses returned by the DNS query are honest then we want the node to be able to (eventually) find and connect to the honest network.

Note that for completeness, if the DNS seed queries are unsuccessful, then bitcoind will fall back to connecting to a hard-coded list of seed nodes.
This fall back functionality is only run as a last resort if all DNS seeds are down (e.g. if there is an attack on the DNS seed infrastructure).

=== Addrman

Every time a node hears about another node in the network, it adds/updates a record in its `AddrMan` (Address Manager).
This is where all the data about nodes in the network is stored, and this is where a `GETADDR` receiver looks to construct an `ADDR` response to the requester.

Addrman has several design goals: We want to have a diverse selection of addresses in order to find good peers to connect to, but also want to be resistant against DOS attacks and
limit the influence of a single source (so that a single peer cannot monopolize our address database).
It consists of two tables, the New tables (where new, unverified addresses are stored) and the Tried tables, where only addresses are stored to which the node has made a successful
outgoing connection at some point in the past.

=== Address relay

The Bitcoin network uses `addr` messages to communicate (node) network addresses.
See the https://en.bitcoin.it/wiki/Protocol_documentation#addr[Bitcoin wiki p2p documentation] for more details.
Good address propagation improves network connectivity and increases the difficulty of executing an eclipse attack.

Bitcoin Core nodes will periodically self-announce (also known as self-advertise) their own network address to peers.
When a Bitcoin Core node receives an `addr` message that contains 10 addresses or fewer, it forwards those addresses with a timestamp within 10 minutes of the current time to 1 or 2 peers, selected at random.
If we assume all nodes do this, then self-announcements should reach a large portion of the nodes on the network. The timestamp condition is there to ensure that the relay of a given address stops after some time.

Since https://github.com/bitcoin/bitcoin/pull/22387[PR#22387], there is a rate limit for address relay, so that addresses from peers that send too many of them are ignored.

=== Eclipse attacks

https://bitcoinops.org/en/topics/eclipse-attacks/[Eclipse attacks] occur when an adversary is able to isolate a victim's node from the rest of the network.
If you're unfamiliar with the concept of eclipse attacks, https://bitcoinops.org/en/topics/eclipse-attacks/[the Optech topics page] contains links to many resources on the subject.

A _restart-based eclipse attack_ occurs when the adversary is able to add its own addresses to the victim's address manager and then force the victim to restart.
If the attack succeeds, the victim will make all of its connections to the adversary's addresses when it restarts.

https://github.com/bitcoin/bitcoin/issues/17326[Issue 17326] proposed persisting the node's outbound connection list to disk, and on restart reconnecting to the same peers.
It's worth reading the full discussion in that issue, since there are a lot of subtle points around which peers should be persisted.

Block-relay-only connections are a type of connection where nodes do not participate in transaction or address relay and only relay blocks. An effective way for a spy node to infer the network topology is to observe the timing and details of transaction and address relay, so these block-relay-only connections obfuscate network topology and help to mitigate eclipse attacks.
Block-relay-only connections were introduced in https://github.com/bitcoin/bitcoin/pull/15759[PR#15759]. After these changes, nodes by default open two outbound block-relay-only connections on startup.
https://github.com/bitcoin/bitcoin/pull/17428[PR#17428] added functionality to preserve outbound block-relay-only connections during restart.

https://github.com/bitcoin/bitcoin/pull/19858[PR#19858] proposes a more advanced use of block-relay-only connections to further mitigate eclipse attacks.
After this PR, the node will periodically initiate an additional block-relay-only connection, and then sync headers to try to learn about new blocks.
If this reveals new blocks, the eviction logic will rotate out an existing block-relay-only connection.
If no new blocks are discovered, the connection is closed.
It's important for this eviction logic to be carefully reviewed.

==== Addrman and eclipse attacks design guide

The concepts involved in how address-based (eclipse) attacks work, how Bitcoin Core manages and tries connections to new (node) addresses, countermeasures deployed to try and prevent naive eclipse attacks, some partially-deployed countermeasures and currently-open research questions can be found in the bitcoin devwiki article https://github.com/bitcoin-core/bitcoin-devwiki/wiki/Addrman-and-eclipse-attacks[Addrman and eclipse attacks].

=== `Addr` privacy

For some time, it was possible for a spy node to easily scrape the full contents of any reachable node's `AddrMan`.
The spy just had to connect to a victim node multiple times and execute `GETADDR`.
This scraped data could then be used to infer private information about the victim.

For example, a spy could monitor the victim's `AddrMan` content in real time and figure out which peers a node is connected to.
A spy could also compare the `AddrMan` content from two different connections (e.g. one identified by Tor address and one identified by IPv4) and figure out that it's actually the same physical node (`fingerprinting`).

https://github.com/bitcoin/bitcoin/pull/18991[PR#18991] was a first step towards fixing these privacy issues.
By limiting (caching) the leaked portion of `AddrMan`, these inference activities became much harder.
Caching in this context means that the `ADDR` response (which is only a small subset of a node's `AddrMan` content) remains the same for every `GETADDR` call during (roughly) a day.

=== Addr black holes

We know that some nodes on the network do _not_ relay `addr` messages that they receive.
Two known cases are block-relay-only connections from Bitcoin Core nodes, and connections from certain light clients.
We refer to these connections as `addr` black holes.
`addr` messages go in, but they never escape!

If a large portion of the connections on the network are `addr` black holes, then `addr` propagation is impacted.
Self-announcements won't reach a majority of nodes on the network.
It'd be better if we could somehow avoid picking black holes as the 1 or 2 peers that we select for relaying `addr` messages to.

https://github.com/bitcoin/bitcoin/pull/21528[PR#21528] defers initialization of `m_addr_known` of inbound peers until the peer sends an address related message (`addr`, `addrv2`, `getaddr` or `sendaddrv2`).
The node uses the presence of `m_addr_known` to decide whether the peer is a candidate for relaying `addr` messages received from the network.

=== addrv2

https://github.com/bitcoin/bitcoin/pull/19031[PR#19031] is a proposed implementation of the https://github.com/bitcoin/bips/blob/9286b5254317d9e73fb25c5f0acd2b2d9937843e/bip-0155.mediawiki[BIP155] `addrv2` message, a new p2p message format proposed in early 2019 by Wladimir J. van der Laan to gossip longer node addresses.

The `addrv2` message is required to support https://trac.torproject.org/projects/tor/wiki/doc/NextGenOnions[next-generation Tor v3 Onion addresses], the https://geti2p.net[Invisible Internet Project (I2P)], and potentially other networks that have longer endpoint addresses than fit in the 128 bits/16 bytes of the current `addr` message.

== `Tx` privacy

If a spy is able to identify which node initially broadcast a transaction, there's a high probability that that node is the source wallet for the transaction.
To avoid that privacy leak, we try to be intentional about how we relay and request transactions.
We don't want to reveal the exact contents of our mempool or the precise timing when we received a transaction.

https://github.com/bitcoin/bitcoin/pull/18861[PR#18861] improved transaction-origin privacy.
The idea is that if we haven't yet announced a transaction to a peer, we shouldn't fulfil any `GETDATA` requests for that transaction from that peer.
The implementation for that PR checks the list of transactions we are about to announce to the peer (`setInventoryTxToSend`), and if it finds the transaction that the peer has requested, then responds with a `NOTFOUND` instead of with the transaction.

[TIP]
====
While this helps in many cases, why is it still an imperfect heuristic?
====

https://github.com/bitcoin/bitcoin/pull/19109[PR#19109] further reduces the possible attack surface.
It introduces a per-peer rolling bloom filter (`m_recently_announced_invs`) to track which transactions were recently announced to the peer.
When the peer requests a transaction, we check the filter before fulfilling the request and relaying the transaction.

=== Rebroadcasting transactions

Hiding links between wallet addresses and IP addresses is a key part of Bitcoin privacy.
Many techniques exist to help users obfuscate their IP address when submitting their own transactions, and various P2P changes have been proposed with the goal of hiding transaction origins.

Beyond initial broadcast, _rebroadcast_ behaviour can also leak information.
If a node rebroadcasts its own wallet transactions differently from transactions received from its peers, adversaries can use this information to infer transaction origins even if the initial broadcast revealed nothing.

==== Rebroadcast project

The rebroadcast project's goal is to improve privacy by making node rebroadcast behaviour for wallet transactions indistinguishable from that of other peers' transactions.

https://github.com/bitcoin/bitcoin/pull/21061[PR#21061] adds a `TxRebroadcast` module responsible for selecting transactions to be rebroadcast and keeping track of how many times each transaction has been rebroadcast.
After each block, the module uses the miner and other heuristics to select transactions from the mempool that it believes "should" have been included in the block and re-announces them (disabled by default for now).

Rebroadcasts happen once per new block.
The set of transactions to be rebroadcast is calculated as follows:

* The node regularly estimates the minimum feerate for transactions to be included in the next block, `m_cached_fee_rate`.
* When a new block arrives, the transactions included in the block are removed from the mempool. The node then uses `BlockAssembler` to calculate which transactions (with a total weight up to 3/4 of the block maximum) from the mempool are more than 30 minutes old and have a minimum feerate of `m_cached_fee_rate`. This results in a set of transactions that our node would have included in the last block.
* The rebroadcast attempt tracker, `m_attempt_tracker`, tracks how many times and how recently we've attempted to rebroadcast a transaction so that we don't spam the network with re-announcements.


== Connections overview

Outbound connections from Bitcoin Core are initiated as part of startup from within https://github.com/bitcoin/bitcoin/blob/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/init.cpp#L1841-L1932[_src/init.cpp_] after the connection manager, `CConnman`, is started via `node.connman->Start()`.

== CConnman

https://github.com/bitcoin/bitcoin/blob/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/net.h#L803[`CConnman`] is the class in net that opens, maintains and closes connections to peers, manages sockets, and reads/writes messages on the network.

Within `CConnman`, we maintain https://github.com/bitcoin/bitcoin/blob/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/net.h#L1137[vNodes], a vector of connections to other nodes.
That vector is updated and accessed by various threads, including:

. The https://github.com/bitcoin/bitcoin/blob/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/net.cpp#L1578[socket handler thread], which is responsible for reading data from the sockets into receive buffers, and also for accepting new incoming connections.
. The https://github.com/bitcoin/bitcoin/blob/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/net.cpp#L1780[open connections thread], which is responsible for opening new connections to peers on the network.
. The https://github.com/bitcoin/bitcoin/blob/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/net.cpp#L2181[message handler thread], which is responsible for reading messages from the receive buffer and passing them up to net_processing.

Since the vector can be updated by multiple threads, it is guarded by a mutex called https://github.com/bitcoin/bitcoin/blob/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/net.h#L1139[cs_vNodes].

// For operations that are done on each connection in turn (e.g. reading from each socket in the socket handler thread, or passing messages to net_processing in the message handler thread), the common pattern is to:
//
// . lock `cs_vNodes`
// . make a copy of the `vNodes` vector
// . for each `CNode` object, increment an internal https://github.com/bitcoin/bitcoin/blob/92758699/src/net.h#L454[nRefCount] atomic counter.
// . release `cs_vNodes`
// . operate on each of the `CNode` objects in the `vNodes` copy in turn
// . decrement the `nRefCount` counter for each `CNode`
//
// This PR proposes to extract that pattern into an https://en.cppreference.com/w/cpp/language/raii[RAII] object called `NodesSnapshot`.
// It also changes the order of some logic in the socket handler thread.
// The motivation is to reduce https://stackoverflow.com/questions/1970345/what-is-thread-contention[lock contentions].

=== Making connections

`CConnman::Start()` will first attempt to bind to any specified bind (and whitebind) addresses (and onion services), along with optional i2p interface setup:

.src/net.cpp#CConnman::Start
[source,cpp,options=nowrap]
----
    if (fListen && !InitBinds(connOptions.vBinds, connOptions.vWhiteBinds, connOptions.onion_binds)) {
        if (clientInterface) {
            clientInterface->ThreadSafeMessageBox(
                _("Failed to listen on any port. Use -listen=0 if you want this."),
                "", CClientUIInterface::MSG_ERROR);
        }
        return false;
    }

    proxyType i2p_sam;
    if (GetProxy(NET_I2P, i2p_sam)) {
        m_i2p_sam_session = std::make_unique<i2p::sam::Session>(GetDataDir() / "i2p_private_key",
                                                                i2p_sam.proxy, &interruptNet);
    }
----

Next we add any addresses supplied via the `-seednode` argument, and then load addresses (if any) from `peers.dat` and finally `anchors.dat`.
`anchors.dat` will be empty on first run but if we are later happy with our connection to the bitcoin network (and have a clean shutdown) our two outbound block-relay-only peers will be saved in this file to aid in connectivity on subsequent program runs.

.src/net.cpp#CConnman::Start
[source,cpp,options=nowrap]
----
    for (const auto& strDest : connOptions.vSeedNodes) {
        AddAddrFetch(strDest);
    }

    // ...

    // Load addresses from peers.dat
    int64_t nStart = GetTimeMillis();
    {
        CAddrDB adb;
        if (adb.Read(addrman))
            LogPrintf("Loaded %i addresses from peers.dat  %dms\n", addrman.size(), GetTimeMillis() - nStart);
        else {
            addrman.Clear(); // Addrman can be in an inconsistent state after failure, reset it
            LogPrintf("Recreating peers.dat\n");
            DumpAddresses();
        }
    }

    if (m_use_addrman_outgoing) {
        // Load addresses from anchors.dat
        m_anchors = ReadAnchors(GetDataDir() / ANCHORS_DATABASE_FILENAME);
        if (m_anchors.size() > MAX_BLOCK_RELAY_ONLY_ANCHORS) {
            m_anchors.resize(MAX_BLOCK_RELAY_ONLY_ANCHORS);
        }
        LogPrintf("%i block-relay-only anchors will be tried for connections.\n", m_anchors.size());
    }
----

Because the networking segment of the code is multi-threaded, two `CSemaphores` are setup next which control the number of connections being made by the node.

.src/net.cpp#CConnman::Start
[source,cpp,options=nowrap]
----
    if (semOutbound == nullptr) {
        // initialize semaphore
        semOutbound = std::make_unique<CSemaphore>(std::min(m_max_outbound, nMaxConnections));
    }
    if (semAddnode == nullptr) {
        // initialize semaphore
        semAddnode = std::make_unique<CSemaphore>(nMaxAddnode);
    }
----

After this we get to the primary thread initialisation.

.src/net.cpp#CConnman::Start
[source,cpp,options=nowrap]
----
    //
    // Start threads
    //

    // Send and receive from sockets, accept connections
    threadSocketHandler = std::thread(&TraceThread<std::function<void()> >, "net", std::function<void()>(std::bind(&CConnman::ThreadSocketHandler, this))); <1>

    if (!gArgs.GetBoolArg("-dnsseed", DEFAULT_DNSSEED))
        LogPrintf("DNS seeding disabled\n");
    else
        threadDNSAddressSeed = std::thread(&TraceThread<std::function<void()> >, "dnsseed", std::function<void()>(std::bind(&CConnman::ThreadDNSAddressSeed, this))); <2>

    // Initiate manual connections
    threadOpenAddedConnections = std::thread(&TraceThread<std::function<void()> >, "addcon", std::function<void()>(std::bind(&CConnman::ThreadOpenAddedConnections, this))); <3>

    if (connOptions.m_use_addrman_outgoing && !connOptions.m_specified_outgoing.empty()) {
        if (clientInterface) {
            clientInterface->ThreadSafeMessageBox(
                _("Cannot provide specific connections and have addrman find outgoing connections at the same."),
                "", CClientUIInterface::MSG_ERROR);
        }
        return false;
    }
    if (connOptions.m_use_addrman_outgoing || !connOptions.m_specified_outgoing.empty())
        threadOpenConnections = std::thread(&TraceThread<std::function<void()> >, "opencon", std::function<void()>(std::bind(&CConnman::ThreadOpenConnections, this, connOptions.m_specified_outgoing))); <4>
----

<1> A thread is spawned which manages the accepting (of new) and disconnecting old connections.
<2> If DNS seeds are not disabled, then a thread is spawned to request addresses from the DNS seeds.
<3> A thread is spawned to initiate manual connections (provided at startup).
<4> A thread to make connections from addresses in `addrman`.

It might appear that DNS seeds are being tried before both manual connections and any addresses found in `peers.dat`, however closer inspection of the 109L function `CConnmann::ThreadDNSAddressSeed` reveals that more than half of those lines are spent trying _not_ to query the DNS seeds, as the rationale in the code comments describes:

.src/net.cpp#CConnman::ThreadDNSAddressSeed
[source,cpp,options=nowrap]
----
// goal: only query DNS seed if address need is acute
// * If we have a reasonable number of peers in addrman, spend
//   some time trying them first. This improves user privacy by
//   creating fewer identifying DNS requests, reduces trust by
//   giving seeds less influence on the network topology, and
//   reduces traffic to the seeds.
// * When querying DNS seeds query a few at once, this ensures
//   that we don't give DNS seeds the ability to eclipse nodes
//   that query them.
// * If we continue having problems, eventually query all the
//   DNS seeds, and if that fails too, also try the fixed seeds.
//   (done in ThreadOpenConnections)
----

We see in that function if we have > 1000 peers in our `addrman` (`DNSSEEDS_DELAY_PEER_THRESHOLD`) we will sleep for 5 minutes (`DNSSEEDS_DELAY_MANY_PEERS`) before querying the DNS seeds, but if we know about fewer than 1000 peers then we will only sleep for 11 seconds (`DNSSEEDS_DELAY_FEW_PEERS`):

.src/net.cpp#CConnman::ThreadDNSAddressSeed
[source,cpp,options=nowrap]
----
const std::chrono::seconds seeds_wait_time = (addrman.size() >= DNSSEEDS_DELAY_PEER_THRESHOLD ? DNSSEEDS_DELAY_MANY_PEERS : DNSSEEDS_DELAY_FEW_PEERS);
----

As described in <<Eclipse attacks>> a risk exists where a malicious DNS seeder eclipses a node by returning an enormous number of IP addresses.
We mitigate this risk by limiting the number of IP addresses addrman learns to 256 per DNS seeder.
Further down in `ThreadDNSAddressSeed()` we see such a magic number:

.src/net.cpp#CConnman::ThreadDNSAddressSeed
[source,cpp,options=nowrap]
----
unsigned int nMaxIPs = 256; // Limits number of IPs learned from a DNS seed
----

TODO: describe connecting to hardcoded seeds after 6 minutes if still `addrman == 0`.

== P2P message encryption

P2P messages are currently all unencrypted which can potentially open up vulnerabilities like:

* Associated metadata in P2P messages may reveal private information.
* Possibilities for attackers who control the routing infrastructure of the P2P network to censor P2P
messages since P2P messages can be detected trivially - they always start with a fixed sequence of magic bytes.

https://gist.github.com/dhruv/5b1275751bc98f3b64bcafce7876b489[BIP 324] proposes a new Bitcoin P2P protocol which features transport encryption and slightly lower bandwidth usage.

https://bip324.com[bip324.com] contains a list of all the open PRs and great resources to understand the proposal.
A visual explanation of how BIP 324 works can be found in this blog - https://github.com/stratospher/blogosphere/blob/main/bip324.md[How to encrypt the P2P protocol?]

=== Networking contribution to node RNG entropy

Entropy for the RNG is often harvested from network connections:

.src/net.cpp
[source,cpp,options=nowrap]
----
net.cpp
488-
489:    // We're making a new connection, harvest entropy from the time (and our peer count)
490-    RandAddEvent((uint32_t)id);
--
743-
744:    // We just received a message off the wire, harvest entropy from the time (and the message checksum)
745-    RandAddEvent(ReadLE32(hash.begin()));
--
1160-
1161:    // We received a new connection, harvest entropy from the time (and our peer count)
1162-    RandAddEvent((uint32_t)id);
----

== Bloom filters and SPV

A https://en.wikipedia.org/wiki/Bloom_filter[bloom filter] is a probabilistic data structure.
It supports two operations:

. _adding_ an element to the filter
. _querying_ an element from the filter

If an element has been previously added, then querying for the element will return _true_.
If an element has not been added, then querying for the element may return _true_ or _false_.
In other words, querying may return a _false positive_, but will never return a _false negative_.

See the https://en.wikipedia.org/wiki/Bloom_filter[wikipedia page] for how a bloom filter is implemented with hash functions onto a bitfield.
Note that the false positive rate depends on the size of the filter and the number of hash functions.

https://github.com/bitcoin/bips/blob/master/bip-0037.mediawiki[BIP 37] introduced a new method for https://developer.bitcoin.org/devguide/operating_modes.html#simplified-payment-verification-spv[Simple Payment Verification (SPV)] clients to use bloom filters to track transactions that affect their addresses.
BIP 37 was implemented in Bitcoin Core in https://github.com/bitcoin/bitcoin/pull/1795[PR#1795].

Using the P2P messages defined in BIP 37, an SPV client can request that a full node send it transactions which match a bloom filter.
The full node will then relay unconfirmed transactions that match the filter, and the client can request https://github.com/bitcoin/bitcoin/blob/608359b071dac82a9cf33a6c9e01f87abfcb90eb/src/merkleblock.h#L127-L132[merkle blocks], which only contain the transactions that match the filter.

The SPV client chooses the bloom filter parameters (filter size, number of hashes and a 'tweak' for the hashes) and sends them to the node in a `filterload` message.

The original implementation contained a logic bug. If the client sent a `filterload` message with a zero-sized filter, then the serving node could later attempt a divide-by-zero and crash when querying an element from the filter. See https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-5700[CVE-2013-5700] for further details.

This bug was quietly fixed in https://github.com/bitcoin/bitcoin/pull/2914[PR#2914] without advertising the reason.
That fix added the `isFull` and `isEmpty` booleans, which have proven to be confusing for developers.

https://github.com/bitcoin/bitcoin/pull/18806[PR#18806] removed those `isFull` and `isEmpty` booleans and adds a more straightforward fix for the issue.

== Blocksonly relay

After a block is mined it is broadcast to the p2p network where it will eventually be relayed to all nodes on the network.
There are two methods available for relaying blocks:

. *Legacy Relay*
** A node participating in legacy relaying will always send or request entire blocks.
** For nodes that maintain a mempool this is quite bandwidth inefficient, since they probably already have most of the transactions from a new block in their mempool.
. *Compact Block Relay*
** Specified in https://github.com/bitcoin/bips/blob/master/bip-0152.mediawiki[BIP 152].
** The goal is to address the bandwidth inefficiencies of legacy relaying by only relaying the transactions of a new block that the requesting peer has not yet seen.
** Check out this https://bitcoincore.org/en/2016/06/07/compact-blocks-faq/[Compact Blocks FAQ] for benchmarks and more info.

Bitcoin Core 0.12 introduced a `-blocksonly` setting that can reduce a node's bandwidth usage by 88%.
The reduction is achieved by not participating in transaction relay.
For more info check out https://bitcointalk.org/index.php?topic=1377345.0[this post] on blocksonly mode by Gregory Maxwell.
Blocksonly nodes currently use compact block relaying to download blocks even though they don't maintain a full mempool.

https://github.com/bitcoin/bitcoin/pull/22340[PR#22340] makes blocksonly nodes use legacy relaying to download new blocks.

As currently implemented block-relay-only connections (introduced in https://github.com/bitcoin/bitcoin/pull/15759[PR#15759]), disables both transaction and address relay.
Bitcoin Core nodes per default settings make two *outbound* block-relay-only connections in addition to 8 regular outbound connections (also see <<Eclipse attacks>> for more use cases of these connections).

=== Notifying peers of relay preferences

Currently, block-relay-only connections are established indirectly:

* When making an outbound block-relay-only connection, a node sets the boolean flag `fRelay` in the version message to `false`.
* `fRelay` (introduced in the context of https://github.com/bitcoin/bips/blob/master/bip-0037.mediawiki[BIP 37]) does not imply that transactions cannot be sent for the entire duration of the connection - in its original use case with BIP37, relay of transactions can be activated later on.
* `fRelay=false` is also used in *-blocksonly* mode, a low-bandwidth option in which a node does not want to receive transactions from *any peer*, but does participate in address relay.

Therefore, nodes currently don't have a notion which of their incoming peers see the connection as block-relay-only and don't have any logic attached to it.

https://github.com/bitcoin/bitcoin/pull/20726[PR#20726], accompanied by the new BIP proposal https://github.com/sdaftuar/bips/blob/2021-02-bip338-fixups/bip-0338.mediawiki[BIP 338], introduces the new p2p message `disabletx` for block-relay-only connections, which makes it explicit that no messages related to transaction relay should ever be exchanged over the duration of the connection.

=== Peer state in the codebase

There are two main data structures that handle peer state: `CNode` (defined in `net.h` and covered by `cs_vNodes`) and `CNodeState` (defined in _netprocessing.cpp_ and covered by `cs_main`).
Roughly speaking, `CNode` is concerned with the _connection_ to the peer, and `CNodeState` is concerned with _application state_ of the peer.
However, there is still some _application state_ contained in `CNode` for historic reasons.
//TODO: has this now been moved?
This should be moved out of `CNode` eventually.
An example of the _application state_ data that is contained in `CNode` is the inventory data protected by `cs_inventory` (see https://github.com/bitcoin/bitcoin/blob/adff8fe32101b2c007a85415c3ec565a7f137252/src/net.h#L716).

== P2P violations

Bitcoin Core has several options for how to treat peers that violate the rules of the P2P protocol:

. Ignore the individual message, but continue processing other messages from that peer
. Increment the peer's "misbehaviour" score, and punish the peer once its score goes above a certain amount
. Disconnect from the peer
. Disconnect from the peer and prevent any later connections from that peer's address (discouragement)

Since https://github.com/bitcoin/bitcoin/pull/20079[PR#20079] we now treat handshake misbehaviour like an unknown message

== Testing P2P changes

It can be challenging to test P2P changes as tooling and functional tests are lacking.
Often devs simply setup a new node with the patch and leave it for some time!?

[TIP]
====
Is there fuzzing for P2P messages yet?
====

=== Testing transaction and block relay under SegWit

SegWit was a softfork defined in https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki[BIP 141], with P2P changes defined in https://github.com/bitcoin/bips/blob/65529b12bb01b9f29717e1735ce4d472ef9d9fe7/bip-0144.mediawiki[BIP 144].

SegWit was activated at block 481,824 in August 2017.
Prior to activation, some very careful testing was carried out to verify different scenarios, for example:

. How are transactions and blocks relayed between un-upgraded and upgraded nodes?
. How do upgraded nodes find other upgraded nodes to connect to?
. If a node is un-upgraded at activation time and subsequently upgrades, how does it ensure that the blocks that it previously validated (without segwit rules) are valid according to segwit rules?

To enable this kind of testing, https://github.com/bitcoin/bitcoin/pull/8418[PR#8418] made it possible to configure the segwit activation parameters using a `-bip9params` configuration option.
That configuration option was later renamed to `-vbparams` in https://github.com/bitcoin/bitcoin/pull/10463[PR#10463], and replaced with `-segwitheight` in https://github.com/bitcoin/bitcoin/pull/16060[PR#16060].

Those options allowed starting a node which would never activate segwit by passing `-vbparams=segwit:0:0` (or later, `-segwitheight=-1`).
This was used in the functional tests to test the node's behaviour across activation.

The segwit mainnet activation was a one-time event.
Now that segwit has been activated, those tests are no longer required.

https://github.com/bitcoin/bitcoin/pull/21090[PR#21090] removed the final tests that made use of `-segwitheight=0`.
With those tests removed, the special casing for `-segwitheight=-1` behaviour can also be removed.
That special casing impacted logic in _net_processing_, _validation_ and _mining_.

== Misc P2P

* empty
