include::p2p.adoc[]

include::p2p-design-philosophy.adoc[]

include::p2p-attacks.adoc[]

include::node-components.adoc[]

include::netgroupmanager.adoc[]

include::addrman.adoc[]

include::bootstrapping.adoc[]

////

=== CConnman

https://github.com/bitcoin/bitcoin/blob/v23.0/src/net.h#L761[`CConnman`^] is the class in net that opens, maintains and closes connections to peers, manages sockets, and reads/writes messages on the network.

// For operations that are done on each connection in turn (e.g. reading from each socket in the socket handler thread, or passing messages to net_processing in the message handler thread), the common pattern is to:
//
// . lock `cs_vNodes`
// . make a copy of the `vNodes` vector
// . for each `CNode` object, increment an internal https://github.com/bitcoin/bitcoin/blob/92758699/src/net.h#L454[nRefCount] atomic counter.
// . release `cs_vNodes`
// . operate on each of the `CNode` objects in the `vNodes` copy in turn
// . decrement the `nRefCount` counter for each `CNode`
//
// This PR proposes to extract that pattern into an https://en.cppreference.com/w/cpp/language/raii[RAII] object called `NodesSnapshot`.
// It also changes the order of some logic in the socket handler thread.
// The motivation is to reduce https://stackoverflow.com/questions/1970345/what-is-thread-contention[lock contentions].

=== Making connections

`CConnman::Start()` will first attempt to bind to any specified bind (and whitebind) addresses (and onion services), along with optional I2P interface setup:

Next we add any addresses supplied via the `-seednode` argument (loaded into `vSeedNodes`), and then load addresses (if any) from `peers.dat` and finally `anchors.dat`.
`anchors.dat` will be empty on first run but if we are later happy with our connection to the bitcoin network (and have a clean shutdown) our two outbound block-relay-only peers will be saved in this file to aid in connectivity on subsequent program runs.

Because the networking segment of the code is multi-threaded, two `CSemaphores` are setup next which control the number of connections being made by the node.

.src/net.cpp#CConnman::Start
[source,cpp,options=nowrap]
----
    if (semOutbound == nullptr) {
        // initialize semaphore
        semOutbound = std::make_unique<CSemaphore>(std::min(m_max_outbound, nMaxConnections));
    }
    if (semAddnode == nullptr) {
        // initialize semaphore
        semAddnode = std::make_unique<CSemaphore>(nMaxAddnode);
    }
----

After this we get to the primary thread initialisation with the following logic:

. A thread (`ThreadSocketHandler`) is spawned which manages the accepting (of new) and disconnecting old connections.
. If DNS seeds are not disabled, then a thread (`ThreadDNSAddressSeed`) is spawned to request addresses from the DNS seeds.
. A thread (`ThreadOpenAddedConnections`) is spawned to initiate manual connections (provided at startup).
. A thread (`ThreadOpenConnections`) to make connections from addresses in `addrman`.

It might appear that DNS seeds are being tried before both manual connections and any addresses found in `peers.dat`, however closer inspection of the 109L function `CConnman::ThreadDNSAddressSeed` reveals that more than half of those lines are spent trying _not_ to query the DNS seeds, as the rationale in the code comments describes:

.src/net.cpp#CConnman::ThreadDNSAddressSeed
[source,cpp,options=nowrap]
----
// goal: only query DNS seed if address need is acute
// * If we have a reasonable number of peers in addrman, spend
//   some time trying them first. This improves user privacy by
//   creating fewer identifying DNS requests, reduces trust by
//   giving seeds less influence on the network topology, and
//   reduces traffic to the seeds.
// * When querying DNS seeds query a few at once, this ensures
//   that we don't give DNS seeds the ability to eclipse nodes
//   that query them.
// * If we continue having problems, eventually query all the
//   DNS seeds, and if that fails too, also try the fixed seeds.
//   (done in ThreadOpenConnections)
----

We see in that function if we have > 1000 peers in our `addrman` (`DNSSEEDS_DELAY_PEER_THRESHOLD`) we will sleep for 5 minutes (`DNSSEEDS_DELAY_MANY_PEERS`) before querying the DNS seeds, but if we know about fewer than 1000 peers then we will only sleep for 11 seconds (`DNSSEEDS_DELAY_FEW_PEERS`):

.src/net.cpp#CConnman::ThreadDNSAddressSeed
[source,cpp,options=nowrap]
----
const std::chrono::seconds seeds_wait_time = (addrman.size() >= DNSSEEDS_DELAY_PEER_THRESHOLD ? DNSSEEDS_DELAY_MANY_PEERS : DNSSEEDS_DELAY_FEW_PEERS);
----

A risk exists where a malicious DNS seeder eclipses a node by returning an enormous number of IP addresses.
We mitigate this risk by limiting the number of IP addresses addrman learns to 256 per DNS seeder.
Further down in `ThreadDNSAddressSeed()` we see such a magic number:

.src/net.cpp#CConnman::ThreadDNSAddressSeed
[source,cpp,options=nowrap]
----
unsigned int nMaxIPs = 256; // Limits number of IPs learned from a DNS seed
----

If after 60 seconds we have not made any connections, then `ThreadOpenConnections` will deserialize the hardcoded seeds and https://github.com/bitcoin/bitcoin/blob/v23.0/src/net.cpp#L1960-L1987[add^] them to xref:addrman.adoc#[addrman]  as candidates for connection.
////

include::message-relay.adoc[]

include::address-relay.adoc[]

include::transaction-relay.adoc[]

include::block-relay.adoc[]

include::relay-preferences.adoc[]

include::p2p-encryption.adoc[]

include::network-entropy.adoc[]

include::peer-state.adoc[]

include::p2p-violations.adoc[]

include::testing-p2p-changes.adoc[]

include::p2p-exercises.adoc[]
