= Mempool

include::mempool-terminology.adoc[]

include::mempool-purpose.adoc[]

include::mempool-lifecycle.adoc[]

include::addition-removal-mempool.adoc[]

include::mempool-unbroadcast.adoc[]

include::mempool-tx-format.adoc[]

include::package-relay.adoc[]

include::pinning-attacks.adoc[]

////

== MemPoolAccept

The `MemPoolAccept` class handles mempool validation for new transactions.

Selecting the best transactions for the resource-constrained mempool involves a trade-off between optimistically validating candidates to identify the highest feerate ones and protecting the node from DoS attacks.
As such, we apply a set of validation rules known as mempool _policy_ in addition to consensus.

We can break down transaction validation checks into a few different classes:

* Consensus vs Policy: These can also be thought of as mandatory vs non-mandatory checks.
These two are not mutually exclusive, but we make efforts to compartmentalize consensus rules.
* Script vs Non-script: Script refers to the instructions and data used to specify and satisfy spending conditions.
We make this distinction because script checking (specifically, signature verification) is the most computationally intensive part of transaction validation.
* Contextual vs Context-Free: The context refers to our knowledge of the current state, represented as https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.h#L459[ChainState^].
Contextual checks might require the current block height or knowledge of the current UTXO set, while context-free checks only need the transaction itself.
We also need to look into our mempool to validate a transaction that spends unconfirmed parents or conflicts with another transaction already in our mempool.

=== Context-free non-script checks

Mempool validation in Bitcoin Core starts off with non-script checks (sometimes called https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.cpp#L668["PreChecks"^], the name of the function in which these checks run).

As a defensive strategy the node starts with context-free and/or easily computed checks.
Here are some examples:

* None of the outputs are trying to send a value https://github.com/bitcoin/bitcoin/blob/v23.0/src/consensus/tx_check.cpp#L26-L29[less than 0 or greater than 21 million BTC^].
* The transaction https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.cpp#L689-L691[isn't a coinbase^], as there can't be any coinbase transactions outside of blocks.
* The transaction isn't https://github.com/bitcoin/bitcoin/blob/v23.0/src/policy/policy.cpp#L93-L95[more than 400,000 weight units^].
+
It's possible for a larger transaction to be consensus-valid, but it would occupy too much space in the mempool.
If we allowed these transactions an attacker could try to dominate our mempool with very large transactions that are never mined.

=== Contextual non-script checks

Perhaps the most obvious non-script contextual check is to https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.cpp#L750-L771[make sure the inputs are available^], either in the current chainstate or an unspent output of an in-mempool transaction.
Instead of looking through the entire blockchain (hundreds of gigabytes stored on disk), Bitcoin Core nodes keep a https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.h#L410-L434[layered cache^] of the available https://github.com/bitcoin/bitcoin/blob/v23.0/src/coins.h#L30[coins^] which is a few gigabytes, much of which can be kept in memory.
To make this process more efficient, coins fetched from disk during mempool validation are https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.cpp#L1370-L1378[kept in memory^] if the transaction is accepted to the mempool.

Timelocks are also checked here - the node fetches the BIP113 Median Time Past and/or block height at the current chainstate to check transaction `nLockTime` and input `nSequence`

=== "Contextual" Script Checks

Transaction https://doxygen.bitcoincore.org/validation_8cpp.html#a6a96a3e1e6818904fdd5f51553b7ea60[script checks^] are actually context-free in isolation; the https://doxygen.bitcoincore.org/class_c_tx_in.html#aba540fd902366210a6ad6cd9a18fe763[`scriptSig`^] and https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#specification[`witness`^] for each input, paired with the https://doxygen.bitcoincore.org/class_c_tx_out.html#a25bf3f2f4befb22a6a0be45784fe57e2[`scriptPubKey`^] in the https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.cpp#L1698[corresponding UTXO^] can be passed into the script interpreter and validated without state.
The https://doxygen.bitcoincore.org/interpreter_8h.html[script interpreter^] simply evaluates the series of opcodes and data based on the arguments passed to it.

The "context" passed to the script interpreter is a set of https://github.com/bitcoin/bitcoin/blob/v23.0/src/script/interpreter.h#L43-L147[script verification flags^] indicating which rules to apply during script verification.
For example, the `OP_CHECKSEQUENCEVERIFY` opcode repurposed `OP_NOP3`.
The script verification flag `SCRIPT_VERIFY_CHECKSEQUENCEVERIFY` instructs the script interpreter https://github.com/bitcoin/bitcoin/blob/v23.0/src/script/interpreter.cpp#L587[to interpret^] the opcode `0xb2` as the instruction to check that the input's `nSequence` is greater than the stack value or as a no-op. Starting at the BIP112 activation height, https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.cpp#L1893-L1896[nodes pass^] `SCRIPT_VERIFY_CHECKSEQUENCEVERIFY=1` into the script interpreter during consensus script checks.

=== Context-free Signature and Script Checks

Mempool validation performs two sets of script checks: https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.cpp#L973[`PolicyScriptChecks`^] and https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.cpp#L1001[`ConsensusScriptChecks`^].
The former runs the script interpreter using consensus and policy flags and caches the signature result (if successful) in the https://github.com/bitcoin/bitcoin/blob/v23.0/src/script/sigcache.cpp#L21-L26[signature cache^].
The latter runs the script interpreter using https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.cpp#L1025[consensus flags only^] and caches the full validation result in the script execution cache, identified by the wtxid and script verification flags.
If a new consensus rule is activated between now and the block in which this transaction is included, the cached result is no longer valid, but this is easily detected based on the script verification flags.

For example, before taproot rules are enforced in consensus, they are in policy (`SCRIPT_VERIFY_TAPROOT` included in policy but not consensus script verification flags); nodes won't relay and accept taproot-invalid version 1 transactions into their mempools, even though they aren't breaking any consensus rules yet.
All script checks will be cached without `SCRIPT_VERIFY_TAPROOT`.
After taproot activation, if a previously-validated transaction is seen, the cache entry's script verification flags won't match current consensus flags, so the node will re-run script checks for that transaction.

The most computationally-intensive part of script validation is signature verification (indicated in a script by opcodes such as `OP_CHECKSIG`), which doesn't change based on context.
To save the node from repetitive work, at the very start of script checks, parts of the transaction are https://github.com/bitcoin/bitcoin/blob/v23.0/src/script/interpreter.cpp#L1423[serialized, hashed, and stored^] in a `PrecomputedTransactionData` struct for use in signature verification.
This is especially handy in transactions that have multiple inputs and/or signatures.
Additionally, the cached result from `PolicyScriptChecks` can be used immediately in `ConsensusScriptChecks`; we almost never need to verify the same signature more than once!

////
