include::script.adoc[]

include::validating-scripts.adoc[]

include::transaction-signing.adoc[]

include::script-cli.adoc[]

include::script-appendix.adoc[]

////

== Removed text

=== Signing scripts

In order to sign for a script we are going to call `SignTransaction()` which has the following signature:

.script/sign.cpp#SignTransaction()
[source,cpp,options=nowrap]
----
bool SignTransaction(CMutableTransaction& mtx, const SigningProvider* keystore, const std::map<COutPoint, Coin>& coins, int nHashType, std::map<int, std::string>& input_errors)
----

This function gets called either via the RPC (`signrawtransactionwithkey`) or from within the wallet, via either `LegacyScriptPubKeyMan` or `DescriptorScriptPubKeyMan` which are ultimately called as part of `CWallet::CreateTransactionInternal()`.
As we can see it takes a `CMutableTransaction` (a mutable version of a `CTransaction`), a  `SigningProvider`, a map of ``COutPoint``s and ``Coin``s and a `sighash`.

In order to sign for the script, we need to be able to "solve" the `ScriptPubKey` on the UTXOs being selected.
This is achieved internally by looping over each coin selected as input, setting `prevPubkey` to the coins `scriptPubkey`, retrieving the `SignatureData` from the coin (signatures and scripts) via `DataFromTransaction()` and then calling `ProduceSignature()`, passing in this information along with with an instance of `MutableTransactionSignatureCreator` as the signature creator, on each coin.

The remainder of the loop then verifies the produced signature using the cached version of the `CTransaction`, `txConst` so as not to repeat potentially expensive signature calculations.

.script/sign.cpp#SignTransaction()
[source,cpp,options=nowrap]
----
    // ...

    bool fHashSingle = ((nHashType & ~SIGHASH_ANYONECANPAY) == SIGHASH_SINGLE);

    // Use CTransaction for the constant parts of the
    // transaction to avoid rehashing.
    const CTransaction txConst(mtx);
    // Sign what we can:
    for (unsigned int i = 0; i < mtx.vin.size(); i++) {
        CTxIn& txin = mtx.vin[i];
        auto coin = coins.find(txin.prevout);
        if (coin == coins.end() || coin->second.IsSpent()) {
            input_errors[i] = "Input not found or already spent";
            continue;
        }
        const CScript& prevPubKey = coin->second.out.scriptPubKey;
        const CAmount& amount = coin->second.out.nValue;

        SignatureData sigdata = DataFromTransaction(mtx, i, coin->second.out);
        // Only sign SIGHASH_SINGLE if there's a corresponding output:
        if (!fHashSingle || (i < mtx.vout.size())) {
            ProduceSignature(*keystore, MutableTransactionSignatureCreator(&mtx, i, amount, nHashType), prevPubKey, sigdata);
        }

        UpdateInput(txin, sigdata);

        // amount must be specified for valid segwit signature
        if (amount == MAX_MONEY && !txin.scriptWitness.IsNull()) {
            input_errors[i] = "Missing amount";
            continue;
        }

        ScriptError serror = SCRIPT_ERR_OK;
        if (!VerifyScript(txin.scriptSig, prevPubKey, &txin.scriptWitness, STANDARD_SCRIPT_VERIFY_FLAGS, TransactionSignatureChecker(&txConst, i, amount, MissingDataBehavior::FAIL), &serror)) {
            if (serror == SCRIPT_ERR_INVALID_STACK_OPERATION) {
                // Unable to sign input and verification failed (possible attempt to partially sign).
                input_errors[i] = "Unable to sign input, invalid stack size (possibly missing key)";
            } else if (serror == SCRIPT_ERR_SIG_NULLFAIL) {
                // Verification failed (possibly due to insufficient signatures).
                input_errors[i] = "CHECK(MULTI)SIG failing with non-zero signature (possibly need more signatures)";
            } else {
                input_errors[i] = ScriptErrorString(serror);
            }
        } else {
            // If this input succeeds, make sure there is no error set for it
            input_errors.erase(i);
        }
    }
    return input_errors.empty();
----

Not every input will be signed for during this loop -- an obvious example would be a multi-signature transaction involving multiple keystores, therefore this function is robust against failing to sign for an input, but everything that this keystore can sign for is, and is also verified.

=== Verifying scripts

=== Standardness

=== Descriptors

Have a descriptor cache for descriptors in _src_script_descriptor.h_:

.src/script/descriptor.h
[source,cpp,options=nowrap]
----

/** \brief Interface for parsed descriptor objects.
 *
 * Descriptors are strings that describe a set of scriptPubKeys, together with
 * all information necessary to solve them. By combining all information into
 * one, they avoid the need to separately import keys and scripts.
 *
 * Descriptors may be ranged, which occurs when the public keys inside are
 * specified in the form of HD chains (xpubs).
 *
 * Descriptors always represent public information - public keys and scripts -
 * but in cases where private keys need to be conveyed along with a descriptor,
 * they can be included inside by changing public keys to private keys (WIF
 * format), and changing xpubs by xprvs.
 *
 * Reference documentation about the descriptor language can be found in
 * doc/descriptors.md.
 */

----

Special functions to parse a get checksums for descriptors.

=== Interpreting scripts

_src/script/interpreter.h_

`BaseSignatureChecker` class is used to check signatures and has functions for the various different signature types allowed:

.src/script/interpreter.h
[source,cpp,options=nowrap]
----
class BaseSignatureChecker
{
public:
    virtual bool CheckECDSASignature(const std::vector<unsigned char>& scriptSig, const std::vector<unsigned char>& vchPubKey, const CScript& scriptCode, SigVersion sigversion) const
    {
        return false;
    }

    virtual bool CheckSchnorrSignature(Span<const unsigned char> sig, Span<const unsigned char> pubkey, SigVersion sigversion, const ScriptExecutionData& execdata, ScriptError* serror = nullptr) const
    {
        return false;
    }

    virtual bool CheckLockTime(const CScriptNum& nLockTime) const
    {
         return false;
    }

    virtual bool CheckSequence(const CScriptNum& nSequence) const
    {
         return false;
    }

    virtual ~BaseSignatureChecker() {}
};
----

This class gets overridden by the `GenericSignatureChecker` or `DeferringSignatureChecker`.

=== Building blocks

==== Keys

==== Redeem script

==== OPCODES

==== Interpreter 

==== SIGHASH flags

==== Script verification flags

In _src/script/bitcoinconsensus.h_

==== Script cache

==== Sig cache


== What is script

Bitcoin addresses that "store" coins are in reality cryptographic challenges that, in order to spend the coins, need to be solved by providing a solution whilst adhering to the rules of the scripting system.

The way that Bitcoin decided to implement such a challenge-response system was by using a script-based language -- called "Bitcoin Script" -- which could be used to both present the challenges, and through which to compose the solutions.

[quote, Satoshi Nakamoto]
____
The script is actually a predicate. It’s just an equation that evaluates to true or false. Predicate is a long and unfamiliar word so I called it script.
____

Usually we refer to the _challenge_ as a "locking script", or in the codebase `ScriptPubKey`, and the _solution_ as the "unlocking script" or `scriptSig`.
Often the locking script itself is hashed before being represented as an address and therefore the full "redeem script" must be retained by the party that generated the address (the receiver), because they will need to provide a full copy of the script along with it's satisfaction in order to spend the coins in the future.

.P2PK script example
[example]
====
The simplest example of this is a public key address, for which the challenge contains a public key and an `OP_CHECKSIG`, and simply requires as its solution a signature (over the transaction data) from the private key corresponding to the public key.
`OP_CHECKSIG` will cause the script interpreter to https://github.com/bitcoin/bitcoin/blob/v23.0/src/script/interpreter.cpp#L1083-L1105[check^] that the pubkey at the top position of the stack (from the script pubkey) corresponds to the signature found at the second-from-top position on the stack (from the scriptsig).
If this evaluates to `true` both items are popped from the stack, and execution is complete.
====

Learn Me a Bitcoin has a https://learnmeabitcoin.com/technical/script[web page^] which demonstrates some common script types, as well as including a run-down of how script is crafted and interpreted.

== What is a script made of

Bitcoin script consists of two components:

. Data
. OPCODES (Operation Codes)

A full list of available (and disabled) OPCODES can be found in https://github.com/bitcoin/bitcoin/blob/v23.0/src/script/script.h#L65-L206[script.h^].

== Building a transaction

When we want to construct a transaction in Bitcoin Core, the general process (excluding fee constraints and coin selection) is as follows.

=== Constructing a transaction

We begin by initialising a new `CMutableTransaction` which we will use to build the transaction.
We use the mutable version of the transaction object as transaction assembly might require adding or removing inputs to satisfy fee constraints, as well as re-ordering of in- and outputs to throw off heuristics related to change addresses.

.primitives/transaction.h
[source,cpp,options=nowrap]
----
/** A mutable version of CTransaction. */
struct CMutableTransaction
{
    std::vector<CTxIn> vin;
    std::vector<CTxOut> vout;
    int32_t nVersion;
    uint32_t nLockTime;
    
    // ...
----

Next we create a vector of ``COutput``s (UTXOs) available for the wallet to select from as transaction inputs, followed by creating a vector of ``CRecipient``s to use as the transaction outputs, which notably includes the `scriptPubKey` for each recipient:

[source,cpp,options=nowrap]
----
struct CRecipient
{
    CScript scriptPubKey;
    CAmount nAmount;
    bool fSubtractFeeFromAmount;
};
----

For each recipient we then create a new `CTxOut` object with the `amount` and `scriptPubkey` and append this to our `CMutableTransaction.vout` vector.

(Optional): Create a change address script for ourselves of the appropriate type.

==== Coin selection

If coin selection is not being used (manual selection of input coins), we select coins to reach the required `amount` from our vector of ``COutput``s (UTXOs) and add them to a set of ``CInputCoin``s.

.wallet/coinselection.h
[source,cpp,options=nowrap]
----
class CInputCoin {
public:
    // ..
    COutPoint outpoint;
    CTxOut txout;
    CAmount effective_value;
    CAmount m_fee{0};
    CAmount m_long_term_fee{0};
    // ..
----

Next we add each selected coin to `CMutableTransaction.vin` as a `CTxIn` and shuffle the `vin` coin order, then lock the wallet and begin to sign the transaction with `CWallet::SignTransaction()`.

=== Signing setup

In order to have our `{Descriptor|Legacy}ScriptPubKeyMan` sign the transaction, we need to pass it a mapping from ``COutput``s to ``Coin``s, in the form: `std::map<COutpoint, Coin>`.

We generate this mapping inside `CWallet::SignTransaction()` which, when called with a `CMutableTransaction` as argument, begins by iterating the vector of ``vin``s in the transaction, using `mapWallet.find()` to locate the previous transaction and return it as a `CWalletTx`, which we use to initialise each `Coin`.

.src/wallet/wallet.cpp
[source,cpp,options=nowrap]
----
bool CWallet::SignTransaction(CMutableTransaction& tx) const
{
    AssertLockHeld(cs_wallet);

    // Build coins map
    std::map<COutPoint, Coin> coins;
    for (auto& input : tx.vin) {
        std::map<uint256, CWalletTx>::const_iterator mi = mapWallet.find(input.prevout.hash);
        if(mi == mapWallet.end() || input.prevout.n >= mi->second.tx->vout.size()) {
            return false;
        }
        const CWalletTx& wtx = mi->second;
        coins[input.prevout] = Coin(wtx.tx->vout[input.prevout.n], wtx.m_confirm.block_height, wtx.IsCoinBase());
    }
    std::map<int, std::string> input_errors;
    return SignTransaction(tx, coins, SIGHASH_ALL, input_errors);
}
----

With our coin map we can loop through every ScriptPubKeyMan available to us and call its `{Descriptor|Legacy}ScriptPubKeyMan->SignTransaction()` function on the coin map.
This has the effect of trying to sign each coin with all available ScriptPubKeyMans in a single pass.
This is actioned by calling `CWallet::SignTransaction()` again, this time including the coin map and sighash type as arguments which calls a different function `SignTransaction()` specialization:

.src/wallet/wallet.cpp
[source,cpp,options=nowrap]
----
bool CWallet::SignTransaction(CMutableTransaction& tx, const std::map<COutPoint, Coin>& coins, int sighash, std::map<int, std::string>& input_errors) const
{
    // Try to sign with all ScriptPubKeyMans
    for (ScriptPubKeyMan* spk_man : GetAllScriptPubKeyMans()) {
        // spk_man->SignTransaction will return true if the transaction is complete,
        // so we can exit early and return true if that happens
        if (spk_man->SignTransaction(tx, coins, sighash, input_errors)) {
            return true;
        }
    }

    // At this point, one input was not fully signed otherwise we would have exited already
    return false;
}
----

The ScriptPubKeyMan will first collect the relevant keys for each coin into a `FlatSigningProvider` and will call `script/sign.cpp#SignTransaction()` on the transaction, passing along the `FlatSigningProvider`.

./wallet/scriptpubkeyman.cpp
[source,cpp,options=nowrap]
----
bool DescriptorScriptPubKeyMan::SignTransaction(CMutableTransaction& tx, const std::map<COutPoint, Coin>& coins, int sighash, std::map<int, std::string>& input_errors) const
{
    std::unique_ptr<FlatSigningProvider> keys = std::make_unique<FlatSigningProvider>();
    for (const auto& coin_pair : coins) {
        std::unique_ptr<FlatSigningProvider> coin_keys = GetSigningProvider(coin_pair.second.out.scriptPubKey, true);
        if (!coin_keys) {
            continue;
        }
        *keys = Merge(*keys, *coin_keys);
    }

    return ::SignTransaction(tx, keys.get(), coins, sighash, input_errors);
}
----

////
