= RPC / REST / ZMQ

TIP: This section has been updated to Bitcoin Core @ https://github.com/bitcoin/bitcoin/tree/v24.0.1[v24.0.1^]

== HTTP Server

Bitcoin Core's https://github.com/bitcoin/bitcoin/blob/v24.0.1/src/httpserver.cpp#L138-L139[HTTP server] is responsible for handling both RPC and REST requests, but not ZMQ.
Since https://github.com/bitcoin/bitcoin/pull/5677[PR#5677] the server is based on https://libevent.org/[libevent2].
Libevent is a general purpose event notification library, but is used in Bitcoin Core specifically for HTTP requests (which it supports natively).

Much (not all) of the libevent interface is hidden behind wrappers.
For example, https://github.com/bitcoin/bitcoin/blob/v24.0.1/src/httpserver.h#L56[`HTTPRequest`] wraps `evhttp_request` and https://github.com/bitcoin/bitcoin/blob/v24.0.1/src/httpserver.h#L154[`HTTPEvent`] wraps https://libevent.org/doc/structevent__base.html[`event_base`].

The relevant workflow for how (for example) an RPC request is handled is roughly as follows:

. The HTTP server receives an RPC command from a caller, creates an `evhttp_request` object and passes its pointer to `http_request_cb()` (this step is completely handled by libevent).
. An `HTTPWorkItem` is https://github.com/bitcoin/bitcoin/blob/v24.0.1/src/httpserver.cpp#L264[created], containing the `evhttp_request` (wrapped in `HTTPRequest hreq`) as well as the path and reference to the handler function (which contains the business logic to be executed to deal with the request).
** There are https://github.com/bitcoin/bitcoin/blob/v24.0.1/src/httprpc.cpp#L301-L304[2 handlers] for RPCs.
** There are https://github.com/bitcoin/bitcoin/blob/v24.0.1/src/rest.cpp#L931-L943[12 handlers] for REST.
. The `HTTPWorkItem` https://github.com/bitcoin/bitcoin/blob/v24.0.1/src/httpserver.cpp#L266[is put on the global] `WorkQueue g_work_queue`, which https://github.com/bitcoin/bitcoin/blob/v24.0.1/src/httpserver.cpp#L338-L344[is processed] by multiple worker threads asynchronously.
. When the handler function of a `HTTPWorkItem` completes successfully, it calls https://github.com/bitcoin/bitcoin/blob/v24.0.1/src/httprpc.cpp#L230[`HTTPRequest::WriteReply()`], which triggers the libevent function https://libevent.org/doc/http_8h.html#a0a77d07263e20733a7562dcd576ad721[`evhttp_send_reply()`], which in turn returns a response to the caller and destroys the `evhttp_request` object.

Endpoints are registered to the HTTP server by calling `RegisterHTTPHandler()`, such as e.g. in https://github.com/bitcoin/bitcoin/blob/v24.0.1/src/httprpc.cpp#L301-L304[`StartHTTPRPC()`].

The HTTP server is initiated and started from `AppInitServers()`, and stopped from `Shutdown()`.

`StartHTTPServer()` https://github.com/bitcoin/bitcoin/blob/v24.0.1/src/httpserver.cpp#L433[adds] a thread for each worker to `g_thread_http_workers`.
These threads will keep running until https://github.com/bitcoin/bitcoin/blob/v24.0.1/src/httpserver.cpp#L118[`WorkQueue::Interrupt()`] sets `running` to `false` and https://github.com/bitcoin/bitcoin/blob/v24.0.1/src/httpserver.cpp#L106[the queue is empty].
