:page-title: Communication chanels
:page-nav_order: 120
:page-parent: Overview and Development Process
=== #bitcoin-core-dev IRC channel

The Bitcoin Core project has an IRC channel `#bitcoin-core-dev` available on the Libera.chat network.
If you are unfamiliar with IRC there is a short guide on how to use it with a client called Matrix https://hackmd.io/ZcCoEDnOSTSqb2RDa7fB8Q[here^].
IRC clients for all platforms and many terminals are available.

"Lurking" (watching but not talking) in the IRC channel can both be a great way to learn about new developments as well as observe how new technical changes and issues are described and thought about from other developers with an adversarial mindset.
Once you are comfortable with the rules of the room and have questions about development then you can join in too!

[NOTE]
====
This channel is reserved for discussion about _development of the Bitcoin Core software only_, so please don't ask general Bitcoin questions or talk about the price or other things which would be off topic in there.

There are plenty of other channels on IRC where those topics can be discussed.
====

There are also regular meetings held on #bitcoin-core-dev which are free and open for anyone to attend.
Details and timings of the various meetings are found https://bitcoincore.org/en/meetings/[here^].

=== Communication

In reality there are no hard rules on choosing a discussion forum, but in practice there are some common conventions which are generally followed:

* If you want to discuss the codebase of the Bitcoin Core implementation, then discussion on either the GitHub repo or IRC channel is usually most-appropriate.
* If you want to discuss changes to the core bitcoin protocol, then discussion on the mailing list is usually warranted to solicit feedback from (all) bitcoin developers, including the many of them that do not work on Bitcoin Core directly.
** If mailing list discussions seem to indicate interest for a proposal, then creation of a BIP usually follows.

If discussing something Bitcoin Core-related, there can also be a question of whether it's best to open an Issue, to first discuss the problem and brainstorm possible solution approaches, or whether you should implement the changes as you see best first, open a PR, and then discuss changes in the PR.
Again, there are no hard rules here, but general advice would be that for potentially-controversial subjects, it might be worth opening an Issue first, before (potentially) wasting time implementing a PR fix which is unlikely to be accepted.

Regarding communication timelines it is important to remember that many contributors are unpaid volunteers, and even if they are sponsored or paid directly, nobody owes you their time.
That being said, often during back-and-forth communication you might want to nudge somebody for a response and it's important that you do this in a courteous way.
There are again no hard rules here, but it's often good practice to give somebody on the order of a few days to a week to respond.
Remember that people have personal lives and often jobs outside of Bitcoin development.
