:page-title: Project roles
:page-nav_order: 160
:page-parent: Overview and Development Process
== Organisation & roles

The objective of the Bitcoin Core Organisation is to represent an entity that is decentralized as much as practically possible on a centralised platform.
One where no single Contributor, Member, or Maintainer has unilateral control over what is/isn't merged into the project.
Having multiple Maintainers, Members, Contributors, and Reviewers gives this objective the best chance of being realised.

=== Contributors

Anyone who contributes code to the codebase is labelled a Contributor by GitHub and also by the community.
As of Version 23.0 of Bitcoin Core, there are > 850 individual Contributors credited with changes.

=== Members

Some Contributors are also labelled as Members of the https://github.com/orgs/bitcoin/people[Bitcoin organisation^].
There are no defined criteria for becoming a Member of the organisation; persons are usually nominated for addition or removal by current Maintainer/Member/Admin on an ad-hoc basis.
Members are typically frequent Contributors/Reviewers and have good technical knowledge of the codebase.

Some members also have some additional permissions over Contributors, such as adding/removing tags on issues and Pull Requests (PRs); however, being a Member **does not** permit you to merge PRs into the project.
Members can also be assigned sections of the codebase in which they have specific expertise to be more easily requested for review as Suggested Reviewers by PR authors.

////
NOTE: It is neither necessary nor desirable to "request reviews" from suggested reviewers in a normal workflow. Doing so without a good reason might be interpreted as being pushy and having the opposite result than intended.
////

=== Maintainers

Some organisation Members are also project Maintainers.
The number of maintainers is arbitrary and is subject to change as people join and leave the project, but has historically been less than 10.
PRs can only be merged into the main project by Maintainers.
While this might give the illusion that Maintainers are in control of the project, the Maintainers' role dictates that they *should not* be unilaterally deciding which PRs get merged and which don't.
Instead, they should be determining the mergability of changes based primarily on the reviews and discussions of other Contributors on the GitHub PR.

Working on that basis, the Maintainers' role becomes largely _janitorial_.
They are simply executing the desires of the community review process, a community which is made up of a decentralized and diverse group of Contributors.

////
A list of Maintainers and suggested Reviewers can be found in the https://github.com/bitcoin/bitcoin/tree/master/REVIEWERS[REVIEWERS^] document.
As the document states, these are *not* the only people who should be reviewing PRs.
The project needs as many reviews on each PR as possible, ideally from a diverse range of Reviewers.
////

=== Organisation fail-safes

It is possible for a "rogue PR" to be submitted by a Contributor; we rely on systematic and thorough peer review to catch these.
There has been https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-September/019490.html[discussion^] on the mailing list about purposefully submitting malicious PRs to test the robustness of this review process.

In the event that a Maintainer goes rogue and starts merging controversial code, or conversely, _not_ merging changes that are desired by the community at large, then there are two possible avenues of recourse:

. Have the Lead Maintainer remove the malicious Maintainer
. In the case that the Lead Maintainer themselves is considered to be the rogue agent: fork the project to a new location and continue development there.

In the case that GitHub itself becomes the rogue entity, there have been numerous discussions about how to move away from GitHub, which have been summarized on the devwiki https://github.com/bitcoin-core/bitcoin-devwiki/wiki/GitHub-alternatives-for-Bitcoin-Core[here^].
This summary came in part from discussions on https://github.com/bitcoin/bitcoin/issues/20227[this^] GitHub issue.
