:page-title: Library structure
:page-nav_order: 50
:page-parent: Architecture
:mermaid-puppeteer-config: ./puppeteer-config.json
== Library structure

Bitcoin Core compilation outputs a number of libraries, some which are designed to be used internally, and some which are designed to be re-used by external applications.
The internally-used libraries generally have unstable APIs making them unsuitable for re-use, but `libbitcoin_kernel` is designed to be re-used by external applications (still a work in progress as part of the https://github.com/bitcoin/bitcoin/issues/27587[libbitcoinkernel project^]).

Bitcoin Core has a https://github.com/bitcoin/bitcoin/blob/master/doc/design/libraries.md[guide^] which describes the various libraries, their conventions, and their various dependencies.

[id=library-dependency-graph]
.Bitcoin library dependency graph
[mermaid, target=bitcoin-lib-dependencies]

....
flowchart TB

bitcoin-cli-->libbitcoin_cli;

bitcoind-->libbitcoin_node;
bitcoind-->libbitcoin_wallet;

bitcoin-qt-->libbitcoin_node;
bitcoin-qt-->libbitcoinqt;
bitcoin-qt-->libbitcoin_wallet;

bitcoin-wallet-->libbitcoin_wallet;
bitcoin-wallet-->libbitcoin_wallet_tool;

libbitcoin_cli-->libbitcoin_util;
libbitcoin_cli-->libbitcoin_common;

libbitcoin_consensus-->libbitcoin_crypto;

libbitcoin_common-->libbitcoin_consensus;
libbitcoin_common-->libbitcoin_crypto;
libbitcoin_common-->libbitcoin_util;

libbitcoin_kernel-->libbitcoin_consensus;
libbitcoin_kernel-->libbitcoin_crypto;
libbitcoin_kernel-->libbitcoin_util;

libbitcoin_node-->libbitcoin_consensus;
libbitcoin_node-->libbitcoin_crypto;
libbitcoin_node-->libbitcoin_kernel;
libbitcoin_node-->libbitcoin_common;
libbitcoin_node-->libbitcoin_util;

libbitcoinqt-->libbitcoin_common;
libbitcoinqt-->libbitcoin_util;

libbitcoin_util-->libbitcoin_crypto;

libbitcoin_wallet-->libbitcoin_common;
libbitcoin_wallet-->libbitcoin_crypto;
libbitcoin_wallet-->libbitcoin_util;

libbitcoin_wallet_tool-->libbitcoin_wallet;
libbitcoin_wallet_tool-->libbitcoin_util;

classDef types fill:green,color:white,stroke:green;
class bitcoin-wallet,bitcoind,bitcoin-cli,bitcoin-qt types
....
**Dependency graph**. Arrows show linker symbol dependencies. `libbitcoin_crypto` depends on nothing and is fundamental. `libbitcoin_util` depends on crypto. `libbitcoin_kernel` depends only on consensus, crypto, and util.

It follows that API changes to the libraries which are internally-facing can be done slightly easier than for libraries with externally-facing APIs, for which more care for compatibility must be taken.
