:page-title: Library structure
:page-nav_order: 50
:page-parent: Architecture
:mermaid-puppeteer-config: ./puppeteer-config.json
== Library structure

Bitcoin Core compilation outputs a number of libraries, some which are designed to be used internally, and some which are designed to be re-used by external applications.
The internally-used libraries generally have unstable APIs making them unsuitable for re-use, but `libbitcoin_kernel` (still a WIP) is designed to be re-used by external applications.

Bitcoin Core has a https://github.com/bitcoin/bitcoin/blob/master/doc/design/libraries.md[guide^] which describes the various libraries, their conventions, and their various dependencies.

[id=library-dependency-graph]
.Bitcoin library dependency graph
[mermaid, target=bitcoion-lib-dependencies]

....
flowchart TB

bitcoin-cli-->libbitcoin_cli;

bitcoind-->libbitcoin_node;
bitcoind-->libbitcoin_wallet;

bitcoin-qt-->libbitcoin_node;
bitcoin-qt-->libbitcoinqt;
bitcoin-qt-->libbitcoin_wallet;

bitcoin-wallet-->libbitcoin_wallet;
bitcoin-wallet-->libbitcoin_common;
bitcoin-wallet-->libbitcoin_util;

bitcoin-node-->libbitcoin_node;
bitcoin-node-->libbitcoin_ipc;
bitcoin-node-->libbitcoin_wallet;

bitcoin-gui-->libbitcoinqt;
bitcoin-gui-->libbitcoin_node;
bitcoin-gui-->libbitcoin_ipc;

libbitcoin_cli-->libbitcoin_common;
libbitcoin_cli-->libbitcoin_util;

libbitcoin_consensus-->libbitcoin_crypto;

libbitcoin_common-->libbitcoin_consensus;
libbitcoin_common-->libbitcoin_util;

libbitcoinkernel-->libbitcoin_crypto;

libbitcoin_node-->libbitcoin_common;
libbitcoin_node-->libbitcoin_util;
libbitcoin_node-->libbitcoin_zmq;

libbitcoinqt-->libbitcoin_cli;
libbitcoinqt-->libbitcoin_wallet;

libbitcoin_util-->libbitcoin_crypto;

libbitcoin_wallet-->libbitcoin_common;

libbitcoin_ipc-->libbitcoin_util;

libbitcoin_zmq-->libbitcoin_util;
libbitcoin_zmq-->libbitcoin_common;

classDef types fill:green,color:white,stroke:green;
class bitcoin-wallet,bitcoind,bitcoin-cli,bitcoin-qt,bitcoin-node,bitcoin-gui types
....
**Dependency graph**. Arrows show linker symbol dependencies. `libbitcoin_crypto` depends on nothing and is fundamental. `libbitcoin_util` depends on crypto. `libbitcoinkernel` (experimental kernel library) depends only on crypto.

It follows that API changes to the libraries which are internally-facing can be done slightly easier than for libraries with externally-facing APIs, for which more care for compatibility must be taken.
