= Week 4 — Wallet and GUI
:toc:
:toclevels: 4

== Concepts

* Wallet architecture
* key management
** HD wallets
** Output script descriptors
* Separation of wallet and node functionality
* Key Management
* Transaction Construction
** Taproot
** SegWit
** Bech32
** PSBT
** Coin selection
** CPFP
** RBF
** Transaction batching
** Adaptor signatures
* Multiwallet
* Hardware wallet interface (HWI)
* QT 

== Source material

=== Wallet architecture

* https://github.com/chaincodelabs/bitcoin-core-onboarding/tree/main/1.1_regions.asciidoc#wallet_region[Bitcoin core onboarding - wallet/] describes the main functions of a wallet, along with some of the differences between legacy and descriptor wallets. 

==== Separation of wallet and node functionality

Both `bitcoind` and `bitcoin-qt` programs use the same source code for wallet, networking, consensus etc.
`bitcoin-qt` is not simply a wallet/gui "frontend" for bitcoind but a stand-alone binary which happens to share much of the same code.
There has been discussion since at least as early as 2014 about https://github.com/bitcoin/bitcoin/issues/3882[splitting wallet code] out from the rest of the codebase, however this has not been completed yet.

The https://github.com/bitcoin-core/bitcoin-devwiki/wiki//Process-Separation[Process Separation] project is tracking development working towards separating out node, wallet and GUI code even further.
In the mean time developers have preferred to focus on improving the organisation of the (wallet) source code within the project and to focus on making wallet code more asynchronous and independent of node code, to avoid locking the node while wallet codepaths are executing.

=== Wallet interfaces

In order to facilitate code separation distinct interfaces between the node and the wallet have been created:

* The node holds a https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/interfaces.cpp#L109[`WalletImpl`] interface to call functions on the wallet.
* The wallet holds a https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/node/interfaces.cpp#L429[`ChainImpl`] interface to call functions on the node.
* The node notifies the wallet about new transactions and blocks through the https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/node/interfaces.cpp#L341[`CValidationInterface`].

=== Overview

Wallets are stored on disk as databases, either using BDB or sqlite format.
These wallets can be one of two types, "legacy" or "descriptor".
Wallets are verified and loaded by `bitcoind/bitcoin-qt`, initialised as `CWallet` objects and then a pointer to their interface is stored in the global vector `vpwallets` which is guarded by the main wallet mutex, `cs_wallets`.
When performing wallet operations `GetWallet` (or `GetWallets`) is often called first with the wallet name as argument, and an `std::shared_ptr` to the desired `CWallet` is returned for the operation to be performed on.

=== Initialisation

The wallet component is initialised through the `WalletInitInterface` class which is specified in https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/walletinitinterface.h#L11-L23[src/walletinitinterface.h].
The member functions are marked as virtual in the `WalletInitInterface` definition, indicating that they are going to be overridden later by a derived class.
Both `walletinit.cpp` and `dummywallet.cpp` include classes which override the member functions of the `WalletInitInterface`.

Also in this file the global `g_wallet_init_interface` is declared which will handle the configured `WalletInitInterface`.

The src tree's https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/Makefile.am#L362-L367[Makefile] describes which of these modules is chosen to override: if `./configure` has been run with the wallet enabled (by default), then `wallet/init.cpp` is added to the sources, otherwise `dummywallet.cpp` is added.

The wallet interface is constructed when `Construct` is called on the `g_wallet_init_interface` object by the https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/init.cpp#L1180-L1189[`AppInitInterfaces` function in init.cpp].
`Construct` first checks that the wallet has not been disabled by a runtime argument and will then call `interfaces::MakeWalletClient` on the node.
This initialises a new `WalletClientImpl` object which is then added to the `node` as both `node.wallet_client` (thereafter used to load or create wallets) and to the list of `node.chain_clients` which are connected to the `node`.

=== Verification

The wallet is first verified (before being started) as part of `AppInitMain` which first https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/init.cpp#L1301-L1305[verifies wallet database integrity] by calling https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/load.cpp#L19-L88[VerifyWallets] via the `WalletClientImpl` override of `client->verify`.
`VerifyWallets` starts by checking that the `walletdir` supplied by argument, or default of `""`, is valid.
Next it loops through all wallets it finds in the `walletdir` and adds them to an `std::set` called `wallet_paths`, first deduplicating them by tracking their absolute paths, and then checking that  the `WalletDatabase` for each wallet exists (or is otherwise constructed successfully) and can be verified.
If this check passes for all wallets, then `VerifyWallets` is complete.

=== Loading

The wallet(s) are loaded  when `client->load` is called on each `node.chain_client` as part of https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/init.cpp#L1728-L1732[init.cpp].

NOTE: There are a number of steps in `init.cpp` that happen before the wallet is loaded, notably the blockchain is synced first. +
This means that wallet operations cannot be called on a wallet which is based on stale blockchain data.

The call to  `load` on the wallet `chain_client` has again been overridden, this time by ``WalletClientImpl``'s https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/load.cpp#L90-L121[`LoadWallets` method].
This function works similarly to `VerifyWallets`, first creating the `WalletDatabase` for each wallet (although this time skipping the verify step) before creating a `CWallet` object from the wallet database object and adding it to the global list of wallets, the vector `vpwallets`, by calling https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/load.cpp#L114[`AddWallet`].
`AddWallet` is defined in https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/wallet.cpp#L98-L108[src/wallet.cpp].

=== Startup

The wallet is finally "started" when (all) `chain_clients` are started in https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/init.cpp#L1939-L1941[init.cpp] which calls the overridden `client->start` method from the `WalletClientImpl` class, resulting in https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/load.cpp#L123-L134[src/wallet/load.cpp::StartWallets] being called.
This calls the `GetWallets` function which returns the vector of pointers to the interfaces for loaded `CWallet` objects (called `vpwallets`).
As part of startup `PostInitProcess` is called on each wallet which, after grabbing the wallet lock `cs_wallet`, adds wallet transactions not yet in a block into our mempool, and conversely updates the wallet transactions with any relevant transactions from the mempool.
Also as part of `StartWallets` `flushwallet` might be scheduled (if configured by argument) and wallet transactions are scheduled to be resent every second (although https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/wallet.cpp#L2104-L2147[delayed upstream with a random timer]).

=== Shutdown

Wallets are "flushed" before shutdown.
As part of `init.cpp#Shutdown()` the `flush` method is called on each member of `node.chain_clients`.
`WalletClientImpl` overrides this method to call `FlushWallets` which makes sure all wallet changes have been successfully flushed to the wallet database.

Finally the `stop` method is called on each member of `node.chain_clients` which is overridden by `StopWallets`, flushing again and this time calling `close` on the database file.

=== Controlling the wallet

As we can see wallet startup and shutdown is largely driven from outside the wallet codebase from `init.cpp`.
This makes sense as `init.cpp` is responsible for starting and stopping program components.

Once the wallet is verified and loaded wallet functionality ceases to be called from `init.cpp`, but instead is controlled using external programs in a number of ways.
This is usually either from `bitcoin-cli`, the standalone `bitcoin-wallet` tool, or the `bitcoin`(-qt) GUI.
Both `bitcoind` and `bitcoin`(-qt) run an RPC server which is ready to respond to wallet commands.
When running `bitcoind` interaction with the RPC server is done via use of the `bitcoin-cli` tool.
When running `bitcoin`(-qt) interaction with the RPC server can be achieved by using the RPC console from inside the GUI, or using the `bitcoin-cli` tool.
If using the native GUI from within `bitcoin`(-qt) then communication with the wallet is done directly via qt's https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/qt/walletmodel.h#L50-L242[`WalletModel` interface].

Commands which can be used to control the wallet via RPC are listed in https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/rpcwallet.cpp#L4584-L4657[rpcwallet.cpp].

=== Wallet via RPC

If we take a look at the https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/rpcwallet.cpp#L2562-L2620[`loadwallet` RPC] we can see similarities to ``WalletClientImpl``'s `LoadWallets` function.
However this time the function will check the `WalletContext` to check that we have a wallet context (in this case a reference to a chain interface) loaded.
Next it will call https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/wallet.cpp#L237-L248[`wallet.cpp#LoadWallet`] which starts by grabbing `g_wallet_loading_mutex` and adding the wallet to `g_loading_wallet_set`, before calling https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/wallet.cpp#L207-L234[`LoadWalletInternal`] which adds the wallet to `vpwallets` and sets up various event notifications.

=== Key management

==== Generating keys with Descriptor wallets

*Legacy wallets* used the "keypool" model which stored a bunch of keys and the wallet would simply iterate over each public key contained in the wallet, and generate a create scriptPubKey (and address) for each type of script the wallet supported.
However this approach has a number of shortcomings, e.g. that one key could have multiple addresses, it was difficult to sign for multisig, most importantly that adding new script functionality meant adding new hardcoded script types into the wallet code _for each new type of script_.
Such an approach was not scalable in the long term, and so a new format of wallet needed to be introduced.

*Descriptor wallets* instead store Output Script (key) "descriptors".
These descriptors can be of any script type, including arbitrary scripts (which might be "unknown" to the wallet), and mean that wallets can generate addresses for any type of (valid) descriptor as desired by the user.
Descriptors not only contain what is needed to generate and address, but they also include all the data needed to "solve" (i.e. spend from) them, i.e. create a valid `scriptSig` (knowledge about which ``redeemScript``s and ``witnessScript``s needed).
The document https://github.com/bitcoin/bitcoin/blob/4b5659c6b115315c9fd2902b4edd4b960a5e066e/doc/descriptors.md[Support for Output Descriptors in Bitcoin Core] provides more details and examples of these output descriptors.

==== ScriptPubkeyManager

* Each wallet can now contain multiple https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/scriptpubkeyman.h#L169[``ScriptPubkeyManager``s], who are in control of managing the ``scriptPubkey``s in a wallet.
* Legacy wallets have an equivalent `LegacyScriptPubkeyMan` class.
* The function `ScriptPubkeyManager::CanProvide()` returns whether a wallet can provide a `SigningProvider` that will be able to sign and make signatures for transactions
* Each `ScriptPubkeyManager` has it's own `IsMine()` function which can be used to determine whether a `CTxOut` belongs to that specific `ScriptPubkeyManager` (and therefore by implication to this wallet).
* A `CWallet` therefore becomes a collection of ``ScriptPubkeyManager``s which are each managing an address type.
** In the current implementation, this means that a default wallet consists of 6 ``ScriptPubkeyManager``s, one for each of combination of {legacy, p2sh and bech32} for {receive and change} addresses.

==== IsMine

The wallet needs a way to determine whether a transaction it learns about belongs to it.
When a new transaction is learned about (either entering into the mempool or in a new block) the wallet is notified through the https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/node/interfaces.cpp#L341[`CValidationInterface`].
This will call the function https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/wallet.cpp#L1182[`CWallet:SyncTransaction()`] which will in turn call https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/wallet.cpp#L1015[`CWallet::AddToWalletIfInvolvingMe()`].
`AddToWalletIfInvolvingMe` will then call `IsMine` on each output in the transaction, checking the return code to see if a transaction belongs to our wallet.

=== Constructing transactions

=== Multiwallet

Work on the https://github.com/bitcoin/bitcoin/projects/2[multiwallet project] means that Bitcoin Core can now handle dynamic loading and unloading of multiple wallets while running.

=== GUI

* Has it's own separate repo at https://github.com/bitcoin-core/gui[bitcoin-core/gui].
* There is useful documentation for developers looking to contribute to the QT side of the codebase found at https://github.com/bitcoin-core/bitcoin-devwiki/wiki//Developer-Notes-for-Qt-Code[Developer Notes for Qt Code].

=== Relation to consensus soft forks

Much of the meat of the recently soft-forked changes (e.g. Taproot) reside not inside consensus code, but rather require improvements to the wallet.

== Exercises

[qanda]

== Removed text

* When adding new wallet features which will be included in the GUI, it can be good practice to first implement them as RPC commands because it's easier to create good test coverage for them.
* Advanced transaction signature operations (e.g. signature aggregation, sighash flags) happen in the wallet code.
