= Week 4 — Wallet and GUI
:toc:
:toclevels: 4
:devwiki-qt: https://github.com/bitcoin-core/bitcoin-devwiki/wiki/Developer-Notes-for-Qt-Code
:devwiki-wallet: https://github.com/bitcoin-core/bitcoin-devwiki/wiki/Wallet-Class-Structure-Changes
:obc-qt-region: https://github.com/chaincodelabs/bitcoin-core-onboarding/blob/main/1.1_regions.asciidoc#qt_region
:obc-wallet-region: https://github.com/chaincodelabs/bitcoin-core-onboarding/blob/main/1.1_regions.asciidoc#wallet_region
:split-wallet: https://github.com/bitcoin/bitcoin/issues/3882
:process-separation-project: https://github.com/bitcoin-core/bitcoin-devwiki/wiki/Process-Separation
:multiwallet-project: https://github.com/bitcoin/bitcoin/projects/2
:bitcoin-core-gui-repo: https://github.com/bitcoin-core/gui
:bitcoin-core-output-descriptors: https://github.com/bitcoin/bitcoin/blob/master/doc.descriptors.md

== Concepts

* Wallet architecture
* key management
** HD wallets
** Output script descriptors
* Separation of wallet and node functionality
* Key Management
* Transaction Construction
** Taproot
** SegWit
** Bech32
** PSBT
** Coin selection
** CPFP
** RBF
** Transaction batching
** Adaptor signatures
* Multiwallet
* Hardware wallet interface (HWI)
* QT 

== Source material

=== Wallet architecture

* {obc-wallet-region}[Bitcoin core onboarding - wallet/] describes the main functions of a wallet, along with some of the differences between legacy and descriptor wallets. 

==== Initialisation
:wallet-init-interface: https://github.com/bitcoin/bitcoin/blob/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/init.cpp#L25-L39
:wallet-init-construct: https://github.com/bitcoin/bitcoin/blob/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/init.cpp#L125-L135
:wallet-client-interface: https://github.com/bitcoin/bitcoin/blob/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/interfaces/wallet.h#L309-L332

The wallet component is initialised through the `WalletInitInterface`.

If the node is running with the wallet enabled, interface methods are overridden in {wallet-init-interface}[src/wallet/init.cpp].
If the node is running with `--disable-wallet` enabled, then a dummy interface for the wallet is loaded which is defined in {wallet-dummy-interface}[src/dummywallet.cpp].
 
==== Separation of wallet and node functionality

Both `bitcoind` and `bitcoin-qt` programs use the same source code for wallet, networking, consensus etc.
`bitcoin-qt` is not simply a wallet/gui "frontend" for bitcoind but a stand-alone binary which happens to share much of the same code.
There has been discussion since at least as early as 2014 about {split-wallet}[splitting wallet code] out from the rest of the codebase, however this has not been completed yet.

The {process-separation-project}[Process Separation] project is tracking development working towards separating out node, wallet and GUI code even further, but progress on this has slowed.
In the mean time developers have preferred to focus on improving the organisation of the (wallet) source code within the project and to focus on making wallet code more asynchronous and independent of node code, to avoid locking the node while wallet code is executing.

==== Wallet interfaces

In order to facilitate code separation distinct interfaces between the node and the wallet have been created:

:wallet-impl: https://github.com/bitcoin/bitcoin/blob/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/interfaces.cpp#L109
:chain-impl: https://github.com/bitcoin/bitcoin/blob/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/node/interfaces.cpp#L429
:CValidationInterface: https://github.com/bitcoin/bitcoin/blob/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/node/interfaces.cpp#L341

* The node holds a {wallet-impl}[`WalletImpl`] interface to call functions on the wallet.
* The wallet holds a {chain-impl}[`ChainImpl`] interface to call functions on the node.
* The node notifies the wallet about new transactions and blocks through the {CValidationInterface}[`CValidationInterface`].

=== Key management

==== Generating keys with Descriptor wallets

Legacy wallets used the "keypool" model which stored a bunch of keys and the wallet would simply iterate over each public key contained in the wallet, and generate a create scriptPubKey (and address) for each type of script the wallet supported.
However approach has a number of shortcomings, e.g. that one key could have multiple addresses, it was difficult to sign for multisig, most importantly that adding new script functionality meant adding new hardcoded script types into the wallet code _for each new type of script_.
Such an approach was not scalable in the long term, and so a new format of wallet needed to be introduced.

Descriptor wallets instead store Output Script (key) "descriptors".
These descriptors can be of any script type, including arbitrary scripts ("unknown" to the wallet), and mean that wallets can generate addresses for any type of (valid) descriptor as desired by the user.
Descriptors not only contain what is needed to generate and address, but they also include all the data needed to "solve" (i.e. spend from) them, i.e. create a valid `scriptSig` (knowledge about which ``redeemScript``s and ``witnessScript``s needed).
The document {bitcoin-core-output-descriptors}[Support for Output Descriptors in Bitcoin Core] provides more details and examples of these output descriptors.

==== ScriptPubkeyManager

:class-ScriptPubkeyManager: https://github.com/bitcoin/bitcoin/blob/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/scriptpubkeyman.h#L169

* Each wallet can now contain multiple {class-ScriptPubkeyManager}[``ScriptPubkeyManager``s], who are in control of managing the ``scriptPubkey``s in a wallet.
* Legacy wallets have an equivalent `LegacyScriptPubkeyMan` class.
* The function `ScriptPubkeyManager::CanProvide()` returns whether a wallet can provide a `SigningProvider` that will be able to sign and make signatures for transactions
* Each `ScriptPubkeyManager` has it's own `IsMine()` function which can be used to determine whether a `CTxOut` belongs to that specific `ScriptPubkeyManager` (and therefore by implication to this wallet).
* A `CWallet` therefore becomes a collection of ``ScriptPubkeyManager``s which are each managing an address type.
** In the current implementation, this means that a default wallet consists of 6 ``ScriptPubkeyManager``s, one for each of combination of {legacy, p2sh and bech32} for receive and change addresses.

==== IsMine

:sync-transaction: https://github.com/bitcoin/bitcoin/blob/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/wallet.cpp#L1182
:add-to-wallet-if-involving-me: https://github.com/bitcoin/bitcoin/blob/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/wallet/wallet.cpp#L1015

The wallet needs a way to determine whether a transaction it learns about belongs to it.
When a new transaction is learned about (either entering into the mempool or in a new block) the wallet is notified thought the {CValidationInterface}[CValidationInterface].
This will call the function {sync-transaction}[`CWallet:SyncTransaction()`] which will in turn call {add-to-wallet-if-involving-me}[`CWallet::AddToWalletIfInvolvingMe()`].
`AddToWalletIfInvolvingMe` will then call `IsMine` on each output in the transaction, checking the return code to see if a transaction belongs to our wallet.


=== Constructing transactions


=== Multiwallet

Work on the {multiwallet-project}[multiwallet project] means that Bitcoin Core can now handle dynamic loading and unloading of multiple wallets while running.

=== GUI

* Has it's own separate repo at {bitcoin-core-gui-repo}[bitcoin-core/gui].

== Exercises

[qanda]

== Removed text

* When adding new wallet features which will be included in the GUI, it can be good practice to first implement them as RPC commands because it's easier to create good test coverage for them.
* Advanced transaction signature operations (e.g. signature aggregation, sighash flags) happen in the wallet code.
